### ISSUE TITLE
tee both stdout and stderr to a file?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/processx#103]
I've been struggling to find a portable solution to run an R script and write its output (stdout + stderr) to a log file and keep showing it in the console. The `tee` tool is standard on Unix-like systems, but not on Windows.

Maybe *processx* could help?

**Comment by krlmlr** [comment]
Got it:

``` r
available::available("tee")
#> ── tee ───────────────────────────────────────────────────────────────────────────────────────────────────────────
#> Name valid: ✔
#> Available on CRAN: ✔ 
#> Available on Bioconductor: ✔
#> Available on GitHub:  ✔ 
#> Bad Words: ✔
#> Abbreviations: http://www.abbreviations.com/tee
#> Wikipedia: https://en.wikipedia.org/wiki/tee
#> Wiktionary: https://en.wiktionary.org/wiki/tee
#> Urban Dictionary:
#>   t-shirt - casual wear for all ages.
#>   Tags: tees shirt tea t-shirt t golf busted bustedtees bag clothing
#>   http://tee.urbanup.com/967963
#> Sentiment:???
```

> Created on 2018-04-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

So this would be a loop that calls `$poll_io()`, `$read_output()` and `$read_error()`?

**Comment by gaborcsardi** [comment]
Btw. can't you already do this with `run` and callbacks for output and error? I think you can.

**Comment by gaborcsardi** [comment]
It is trickier if the process is in the bg, though, but then you cannot really poll, either.

**Comment by krlmlr** [comment]
Callbacks from `run()` should work, yes.

The callback I have in mind would store stdout and stderr in the same file. Would you consider changing the interface of `run()` to

```r
run(command = NULL, args = character(), error_on_status = TRUE,
  echo_cmd = FALSE, echo = FALSE, spinner = FALSE, timeout = Inf,
  stdout_line_callback = callback$[["stdout_line"]], stdout_callback = callback$[["stdout"]],
  stderr_line_callback = callback$[["stderr_line"]], stderr_callback = callback$[["stderr"]],
  windows_verbatim_args = FALSE, windows_hide_window = FALSE,
  encoding = "", callback = NULL)
```

to support a single R6 `callback` object?

**Comment by krlmlr** [comment]
Done, for now only for `callr::r()`: https://github.com/krlmlr/tee.
