### ISSUE TITLE
Build failure with Intel compiler

### ISSUE THREAD

**Issue by mdekstrand** [r-lib/processx#109]
This is the processx version of r-lib/callr#50, putting this here to track a copy of the compiler error when building processx (current CRAN version) on the Intel compiler:

```
** libs
icc -std=c99 -qopenmp -O3 -ipo -xHost -multiple-processes  -Wall tools/px.c -o tools/px
tools/px.c(76): warning #266: function "usleep" declared implicitly
        if (fnum > 0) usleep(fnum * 1000.0 * 1000.0);
                      ^

icc -std=c99 -qopenmp -O3 -ipo -xHost -multiple-processes  supervisor/supervisor.c supervisor/utils.c -o supervisor/supervisor
supervisor/supervisor.c(87): warning #266: function "usleep" declared implicitly
      usleep(milliseconds * 1000);
      ^

supervisor/supervisor.c(130): warning #266: function "kill" declared implicitly
      int res = kill(pid, 0);
                ^

supervisor/supervisor.c(152): warning #266: function "kill" declared implicitly
          kill(children[i], SIGTERM);
          ^

supervisor/supervisor.c(199): warning #266: function "kill" declared implicitly
              kill(children[i], SIGKILL);
              ^

supervisor/supervisor.c(328): warning #266: function "fileno" declared implicitly
      if (fcntl(fileno(fp_input), F_SETFL, O_NONBLOCK) == -1) {
                ^

supervisor/supervisor.c(347): error: incomplete type is not allowed
      struct sigaction sa;
                       ^

supervisor/supervisor.c(349): warning #266: function "sigemptyset" declared implicitly
      sigemptyset(&sa.sa_mask);
      ^

supervisor/supervisor.c(350): warning #266: function "sigaction" declared implicitly
      if (sigaction(SIGINT, &sa, NULL)  == -1 ||
          ^

icc: error #10298: problem during post processing of parallel object compilation
compilation aborted for supervisor/supervisor.c (code 2)
make: *** [supervisor/supervisor] Error 2
ERROR: compilation failed for package ‘processx’
```

**Comment by mdekstrand** [comment]
I have done some more research trying to dive into the cause, and it seems that ICC is not picking up some defines that GCC sets up by default.

If I add to `~/.R/Makevars`:

     CFLAGS += -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L

Then it builds correctly.

At this point, I am not sure if this remains a bug - since the code depends on definitions guarded by these macros but does not ensure they are defined - or if it is just a Thing To Note when building with `icc`.

**Comment by gaborcsardi** [comment]
If these are indeed needed, then processx should set them. I'll add them. Thanks!

**Comment by gaborcsardi** [comment]
Unfortunately these flags fail on Solaris: https://artifacts.r-hub.io/processx_3.0.3.9000.tar.gz-1ec3f94c98f74c95a278c8b40a737fbb/processx.Rcheck/00install.out

**Comment by gaborcsardi** [comment]
Btw.  most of these are warnings, there is only one error, and I might be able to fix  that.

**Comment by gaborcsardi** [comment]
@mdekstrand Can you please try the laster commit?

**Comment by mdekstrand** [comment]
With the latest commit, and no settings in my `Makevars`, I get the following:

```
** libs
icc -std=c99 -qopenmp -O3 -ipo -xHost -multiple-processes  supervisor/supervisor.c supervisor/utils.c \
      -o supervisor/supervisor
icc -std=c99 -I"/home/mekstrand/opt/R-3.5.0-intel/lib64/R/include" -DNDEBUG  -I"/home/mekstrand/opt/R-3.5.0-intel/lib64/R/library/testthat/include" -I/usr/local/include   -fpic  -qopenmp -O3 -ipo -xHost -multiple-processes  -c init.c -o init.o
In file included from processx.h(34),
                 from init.c(5):
unix/processx-unix.h(20): error: identifier "siginfo_t" is undefined
  void processx__sigchld_callback(int sig, siginfo_t *info, void *ctx);
                                           ^

icc: error #10298: problem during post processing of parallel object compilation
compilation aborted for init.c (code 2)
make: *** [init.o] Error 2
```

**Comment by gaborcsardi** [comment]
Can you pls give another try?

**Comment by gaborcsardi** [comment]
I am closing this, please reopen if you have issues.

**Comment by dendroica** [comment]
I am trying to install processx in R 3.5.0 on a HPC system (running Linux), so FYI I don't have admin privileges, etc. I get the following error message...

tools/px.c(76): warning #266: function "usleep" declared implicitly
        if (fnum > 0) usleep((useconds_t) (fnum * 1000.0 * 1000.0));
                      ^

tools/px.c(76): error: identifier "useconds_t" is undefined
        if (fnum > 0) usleep((useconds_t) (fnum * 1000.0 * 1000.0));

**Comment by gaborcsardi** [comment]
Can you try this workaound? https://github.com/r-lib/processx/pull/136#issuecomment-404500491
