### ISSUE TITLE
Remove `$restart()`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/processx#116]
Not very useful and it complicates things a lot.

**Comment by rickhelmus** [comment]
[rant]I just spent the whole night figuring why AppVeyor suddenly failed with `attempt to apply non-function`. Maybe first do a `.Deprecated()` in the future?[/rant]

Sorry for that, still loving `processx` ;-) Anyway, I guess the new way is to simply re-create the object? I'm using `restart()` here and there to restart processes after a failure (e.g. a network timeout).

**Comment by gaborcsardi** [comment]
@rickhelmus sorry. `.Deprecated` was not really an option because `restart()` was already not implemented for some of the new features. But yeah, I could have added a method that just throws an error that says the `restart` was removed.

Yeah, I would just write a function starts the process with the parameters you need, and if you need to restart it, just call the function again.

**Comment by rickhelmus** [comment]
Thanks for the speedy reply!

Makes sense, probably would've done the same... so please ignore my previous rant.
