### ISSUE TITLE
wildcards in arguments

### ISSUE THREAD

**Issue by joelnitta** [r-lib/processx#130]
I'm trying to use `processx::run()` on arguments that include wildcards. However, the behavior seems inconsistent -- some commands work, others don't. I think it may have something to do with how things are being quoted by `shQuote`, but I can't figure it out.

For example, these all work:

`processx::run(command = "echo", args = here::here())`

`processx::run(command = "echo", args = here::here("*"))`

`processx::run(command = "ls", args = here::here())`

But this doesn't:

`processx::run(command = "ls", args = here::here("*"))`

"Error in processx::run(command = "ls", args = here::here("*")) : System command error"

FWIW, these all work too:

`system2("ls", here::here("*"))`

`system2("ls", here::here())`

`system(paste("ls", here::here()))`

`system(paste("ls", here::here("*")))`

**Comment by gaborcsardi** [comment]
On Unix the shell  is doing the wildcard expansion, but processx does not use a shell. If you want to start a shell, you have to do that explicitly, i.e.:

```
run("/bin/sh", c("-c", "ls *"))
```

processx does no quoting at all on Unix, so no  shQuote is involved or needed.
