### ISSUE TITLE
warn users run(args = ) cannot include spaces

### ISSUE THREAD

**Issue by maxheld83** [r-lib/processx#137]
Let's say I want to run `ls -a -l`.

Obviously, this is not the same as `ls '-a -l'` (that errors out, because the flags are not treated as, well, flags).

I ran myself into circles by doing something boneheaded like this:

```
processx::run(command = "ls", args = "-a -l", echo_cmd = TRUE)
```

which runs the command `Running ls '-a -l'` and deservedly fails.

I (kinda, sorta?) understand why this was stupid on my part (probably the escaping by `base::shQuote()`).

However, I got confused, because `system2()` *behaves differently*.

```
system2(command = "ls", args = '-a -l')
```

will actually **work**!

I understand this might be related to [this bug in system2](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16127), and anyway, that processx is supposed to be better than this.

Still, I wondered whether other people might also run into this, transitioning from `system2()` to `processx::run()`, and so might benefit from a warning in the docs.

If you agree, I'll try and add a short PR to that effect.

I understand (maybe? a little?) why this behavior is necessary to

**Comment by gaborcsardi** [comment]
`-a` and  `-l` are two separate arguments, so it is  
```r
processx::run(command = "ls", args = c("-a", "-l"), echo_cmd = TRUE)
```

**Comment by maxheld83** [comment]
Sorry yeah I get that. My point was that system2() is behaving differently and this might be confusing for people.

**Comment by maxheld83** [comment]
Ok thanks! Might’ve been just me anyway.
