### ISSUE TITLE
conn_create_file(read = TRUE) problems

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/processx#156]
Hi @gaborcsardi! Running into an issue with `conn_create_file()`.

I'm on Mac High Sierra, R 3.4.4, with the new CRAN version of `processx`.

Am I crazy, or should this work?

``` r
library(processx)
tmp <- tempfile(fileext = ".txt")
conn_create_file(tmp, read = TRUE)
#> Error in conn_create_file(tmp, read = TRUE): Cannot open file `/var/folders/ln/vjgktwwx50jcvm7jq7jlnsbr0000gn/T//RtmpXaFa7U/file8d52a497b73.txt`: `No such file or directory`
```

Created on 2018-09-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I did notice that none of your tests actually look at the `read = TRUE` case so that makes me think there could be a bug. `write = TRUE` by itself does work for me.

**Comment by DavisVaughan** [comment]
Hmm, okay after a bit or trial and error I can get this to work (note that I had to normalize the path)

``` r
library(processx)
tmp <- normalizePath("~/Desktop/R/multi-process-read-write/tester.txt")
conn_create_file(tmp, read = TRUE)
#> <pointer: 0x7fa09be96b30>
#> attr(,"class")
#> [1] "processx_connection"
```

This is interesting (and unrelated to processx)

``` r
normalizePath(tempfile())
#> Warning in normalizePath(tempfile()): path[1]="/var/folders/ln/
#> vjgktwwx50jcvm7jq7jlnsbr0000gn/T//RtmptqN524/file9807d702d12": No such file
#> or directory
#> [1] "/var/folders/ln/vjgktwwx50jcvm7jq7jlnsbr0000gn/T//RtmptqN524/file9807d702d12"
```

**Comment by DavisVaughan** [comment]
Okay so I need to actually create the file. sigh.

``` r
library(processx)
tmp <- tempfile()
file.create(tmp)
#> [1] TRUE
conn_create_file(tmp, read = TRUE)
#> <pointer: 0x7fd6b3d1c830>
#> attr(,"class")
#> [1] "processx_connection"
```

Created on 2018-09-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gaborcsardi** [comment]
Well, yeah, I guess if you are trying to read from a file that does not exist, then `No such file or directory` is a reasonable error message. :)

Btw. if you are using these functions, note the warning in the manual:

>     These functions are currently experimental and will change in the
>     future. Note that processx connections are _not_ compatible with
>     R's built-in connection system.

At some point processx will have (or use) a complete connection system, but that'll take some moe time.

**Comment by DavisVaughan** [comment]
Thanks for the extra heads up! Just kicking the tires for the moment.
