### ISSUE TITLE
Need to link with -lxnet on Solaris

### ISSUE THREAD

**Issue by jeroen** [r-lib/processx#159]
Not sure how CRAN does this but on my Solaris I need `PKG_LIBS=-lxnet` for [socketpair](https://docs.oracle.com/cd/E26502_01/html/E29035/socketpair-3xnet.html),

**Comment by jeroen** [comment]
Are you on Solaris 10 or 11?

**Comment by gaborcsardi** [comment]
Oracle Solaris 10, x86, 32 bit, Oracle compilers.

**Comment by jeroen** [comment]
Ah okay I'm using GCC. Do the oracle compilers support c++11 now?

**Comment by jeroen** [comment]
It's not important, just wasn't sure why it was failing for me. Probably oracle compilers link this in by default.
