### ISSUE TITLE
Is it possible to tell if msys2 bash is "ready" for input

### ISSUE THREAD

**Issue by kendonB** [r-lib/processx#163]
As opposed to waiting for a previous command to complete. The behaviour would be something like:

```r
p <- processx::process$new("c:\\msys64\\usr\\bin\\bash.exe", 
                           stdin = "|", stdout = "|", stderr = "|")
p$write_input("sleep 20\n")

p$is_ready_for_input()
 > FALSE
```

**Comment by gaborcsardi** [comment]
You can write just fine, it goes in a pipe. 

When the pipe is full, `write_input()` will return the characters (raw bytes) that it could not write, so you'll need to try those again later.

**Comment by kendonB** [comment]
Great thanks. Follow up question: is it possible to tell if the bash session is done with a previous command if that command has no std output?

**Comment by gaborcsardi** [comment]
There are some not very good ways, and most probably you don't want to go that way. It is better to just make bash output something to stdout or stderr, or even to another connection and poll for that from R.

Or you can just close the input connection after sending the command, and bash will quit when it is done. Then you can start another bash process later.

**Comment by kendonB** [comment]
When you say "make bash output something", do mean something is simple/hacky as: `p$write_input("ls -a\n")` then waiting for output?

**Comment by gaborcsardi** [comment]
Btw. if you are calling Python, do you know about the reticulate package, that often makes it much simpler, than using subprocesses.

**Comment by kendonB** [comment]
Mm good to know - hadn't seen `reticulate`. I'm using command line utilities written in python - does `reticulate` also handle those nicely?

**Comment by gaborcsardi** [comment]
It embeds the python interpreter into the R process, which is usually much better than subprocesses.
