### ISSUE TITLE
RStudio sporadically crashing when using processx

### ISSUE THREAD

**Issue by kendonB** [r-lib/processx#164]
When using:

Windows 10
RStudio 1.1.453
Latest MSYS2
And commands:
```
p <- processx::process$new("c:\\msys64\\usr\\bin\\bash.exe", 
                           stdin = "|", stdout = "|", stderr = "|")
# many times
p$write_input("<various inputs>")
# many times
p$read_output_lines()
```

Questions:
1) Does anyone have any experience with this symptom? (possibly related: https://github.com/r-lib/processx/issues/90)
2) Does anyone have any advice to help me troubleshoot and be more helpful to the writers of this package?

**Comment by kendonB** [comment]
Apologies - the exact inputs are calls to the `planet` and `pclip` python packages' command line interfaces (always with `\n`) within a large R function. I'm not sure that sharing it is likely to illuminate the discussion. The crashes happen relatively rarely - maybe once every 100-200.

**Comment by gaborcsardi** [comment]
Well, can you write some piece of code that I can run and reproduces the error?

**Comment by kendonB** [comment]
Unfortunately no. The crashes are sporadic - i.e. not reliably reproducible.

**Comment by gaborcsardi** [comment]
Btw, does it also crash from RTerm or RGui? Or really just from RStudio?

**Comment by kendonB** [comment]
I will try the infinite loop

**Comment by kendonB** [comment]
> Btw, does it also crash from RTerm or RGui? Or really just from RStudio?
I can try these others and see how it goes

**Comment by kendonB** [comment]
So leaving it on for ages doesn't seem to reliably crash RStudio. Each time it has happened since I started this issue I have left something running in RStudio downloading a bunch of data using `processx`, then came back, made a (R only) code change, reran the code, and the R session within RStudio crashes instantly. I've tried a few times with RTerm and RGui with no crashes.

**Comment by kendonB** [comment]
Going to close this until I can get some reliable crashing going.

**Comment by kendonB** [comment]
Quick update: I changed the code to open a new process for every download call. I still see the crashing but only on the first download or not at all. So, what I see is RStudio/R/processx playing nicely for extended periods or instantly crashing when I start the downloader going.
