### ISSUE TITLE
Escape quotation marks from args in function processx::run

### ISSUE THREAD

**Issue by vrodriguezf** [r-lib/processx#172]
Hi,

I am trying to execute a command line tool that needs to set one of the parameters as `""`, but I am unable to execute it properly using processx. 

As an example, I would like to execute the command `echo ""`. If I try to put the argument as `''""'`, the command sent to the terminal is the following:
```r
> result = processx::run(command = "echo", args = '""', echo_cmd = T)
Running echo '""'
```

The command is the same if I try to escape the quotation marks using the backslash symbol `\`:
```r
> result = processx::run(command = "echo", args = "\"\"", echo_cmd = T)
Running echo '""'
```

What can I do to execute exactly `echo ""`?

Thank you!!

**Comment by gaborcsardi** [comment]
processx arguments do not need quoting, so it is just
```r
processx::run("echo", "")
```

**Comment by vrodriguezf** [comment]
Then the command is written as:
```r
> result = processx::run(command = "echo", args = "", echo_cmd = T)
Running echo 
```

I need explicitly the presence of the characters `""` in the system call. Is it possible?

Thanks!

**Comment by gaborcsardi** [comment]
Yes, it is explicitly there, it is an empty string. E.g. 
```r
cat("echo $#\n", file = tmp <- tempfile())
Sys.chmod(tmp, "755")
processx::run(tmp, "")
#> $status
#> [1] 0
#>
#> $stdout
#> [1] "1\n"
#>
#> $stderr
#> [1] ""
#> 
#> $timeout
#> [1] FALSE
```

**Comment by gaborcsardi** [comment]
Or another way to see this:
```
ret <- processx::run("R", c("-q", "-e", "commandArgs()", "--args", "", "", ""))
cat(ret$stdout)
#> > commandArgs()
#> [1] "/Library/Frameworks/R.framework/Resources/bin/exec/R"
#> [2] "-q"
#> [3] "-e"
#> [4] "commandArgs()"
#> [5] "--args"
#> [6] ""
#> [7] ""
#> [8] ""
```

**Comment by gaborcsardi** [comment]
Or maybe I don't understand what you are trying to do.

**Comment by vrodriguezf** [comment]
Well, I will show you my actual scenario instead of the toy example with `echo`, just to explain myself a little bit better.

I want to execute the following command:
```
java -Xms512m -Xmx16384m -jar /home/victor/SPMF/spmf.jar run TKS /home/victor/Github/mlr/inst/extdata/inputSPMF.txt  /home/victor/Github/mlr/inst/extdata/outputSPMF.txt 15 2 10 "" 1
```

Note that the penultimate argument is `""`. Now, in R, with processx:
```r
JAVA_OPTIONS = c("-Xms512m", "-Xmx16384m")
SPMF_JAR_FILEPATH = "/home/victor/SPMF/spmf.jar"
SPMF_INPUT_FILEPATH = "/home/victor/Github/mlr/inst/extdata/inputSPMF.txt"
SPMF_OUTPUT_FILEPATH = "/home/victor/Github/mlr/inst/extdata/outputSPMF.txt"
SPMF_ALGORITHM_NAME = "TKS"
SPMF_CALL_ARGUMENTS = c("15", "2", "10", "", 1)
spmf_result = processx::run("java", c(JAVA_OPTIONS, "-jar", SPMF_JAR_FILEPATH,
  "run", SPMF_ALGORITHM_NAME, SPMF_INPUT_FILEPATH, SPMF_OUTPUT_FILEPATH, SPMF_CALL_ARGUMENTS),
  wd = NULL, echo_cmd = TRUE, echo = TRUE)
```
Executing this code shows the following into the screen:
```
Running java -Xms512m -Xmx16384m -jar /home/victor/SPMF/spmf.jar run TKS /home/victor/Github/mlr/inst/extdata/inputSPMF.txt \
  /home/victor/Github/mlr/inst/extdata/outputSPMF.txt 15 2 10  1
```

Note that the penultimate parameter is now missing.

That's what I am referring to.

Best!

**Comment by vrodriguezf** [comment]
Ok, nevermind. I have just realized what it is the problem.

Although the output of `echo_cmd = TRUE` does not show the quotation marks, internally they are being used explicitly, just as you said. I tested it comparing the results of using directly a shell or processx.

So yes, using just `""` solves the issue.

Thank you!!

**Comment by gaborcsardi** [comment]
Yeah, I would say this is a buglet in `echo_cmd`.
