### ISSUE TITLE
Running daemon on Windows 

### ISSUE THREAD

**Issue by fproske** [r-lib/processx#173]
Hello,

first of all many thanks for this great package. I am currently having trouble generating a daemonized process under Windows. When I set `cleanup` to `FALSE`, the process no longer runs in the background, but creates a new prompt (his does not happen when `cleanup` is `TRUE`). Is there a way to avoid this? Any help is very welcome!

Best regards,
Freddy

**Comment by gaborcsardi** [comment]
It really depends on the process you want to run. Some processes are just not happy  running as a daemon. What exactly are you trying to run?

**Comment by gaborcsardi** [comment]
I will close this now. Please re-open with more information if you still have problems.
