### ISSUE TITLE
Processx unknown installation error

### ISSUE THREAD

**Issue by akashpal-21** [r-lib/processx#175]
Hello, i am trying to install Tidyverse, during installation package "callr" returned an error, so i tried to diagnose the issue by seprately installing it,
While doing so, its dependency "processx" returned an installation error. I tried searching online for the error but without no avail.
Here is the installation log.

```
install.packages("callr")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependency ‘processx’

trying URL 'https://cloud.r-project.org/src/contrib/processx_3.2.1.tar.gz'
Content type 'application/x-gzip' length 101057 bytes (98 KB)
==================================================
downloaded 98 KB

trying URL 'https://cloud.r-project.org/src/contrib/callr_3.1.1.tar.gz'
Content type 'application/x-gzip' length 41273 bytes (40 KB)
==================================================
downloaded 40 KB

* installing *source* package ‘processx’ ...
** package ‘processx’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -Wall tools/px.c -o tools/px
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  supervisor/supervisor.c supervisor/utils.c \
      -o supervisor/supervisor
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c poll.c -o poll.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c processx-connection.c -o processx-connection.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c processx-vector.c -o processx-vector.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c create-time.c -o create-time.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c base64.c -o base64.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/childlist.c -o unix/childlist.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/connection.c -o unix/connection.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/processx.c -o unix/processx.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/sigchld.c -o unix/sigchld.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/utils.c -o unix/utils.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QoNLjt/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/named_pipe.c -o unix/named_pipe.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o processx.so init.o poll.o processx-connection.o processx-vector.o create-time.o base64.o unix/childlist.o unix/connection.o unix/processx.o unix/sigchld.o unix/utils.o unix/named_pipe.o -L/usr/lib/R/lib -lR
installing via 'install.libs.R' to /usr/local/lib/R/site-library/processx
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘processx’:
 .onLoad failed in loadNamespace() for 'processx', details:
  call: ps::ps_handle()
  error: Unknown errorfs_error0NA
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/processx’
ERROR: dependency ‘processx’ is not available for package ‘callr’
* removing ‘/usr/local/lib/R/site-library/callr’

The downloaded source packages are in
        ‘/tmp/RtmpcOOSxJ/downloaded_packages’
Warning messages:
1: In install.packages("callr") :
  installation of package ‘processx’ had non-zero exit status
2: In install.packages("callr") :
  installation of package ‘callr’ had non-zero exit status
>
```
I dont know if this is the right place to post this, but if you can help me, i would be very grateful.
Thank you in advance.

Also here are my info:

```

sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: arm-unknown-linux-gnueabihf (32-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /usr/lib/arm-linux-gnueabihf/blas/libblas.so.3.8.0
LAPACK: /usr/lib/arm-linux-gnueabihf/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2    ps_1.3.0
```

**Comment by gaborcsardi** [comment]
Can you check that you have a working ps installation?

**Comment by akashpal-21** [comment]
I am sorry, and thank you for your valuable time.
The problem exists because i think the way my system is installed, no process can acess any files in /proc. 
And as to why, took me some tinkering to figure that by myself (not very good with systems). 
https://github.com/termux/termux-app/issues/299.
Anyways, there does not seem to be any problem with processx, so i can close this issue, i suppose, and once again thank you for your valuable time.

**Comment by osmansharifi** [comment]
install.packages("processx")

  There is a binary version available but the source version is later:
         binary source needs_compilation
processx  3.7.0  3.8.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source package ‘processx’

trying URL 'https://cran.rstudio.com/src/contrib/processx_3.8.0.tar.gz'
Content type 'application/x-gzip' length 162539 bytes (158 KB)
==================================================
downloaded 158 KB

* installing *source* package ‘processx’ ...
** package ‘processx’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -Wall -g -O2  -L/usr/local/lib -Wall tools/px.c -o tools/px
tools/px.c:11:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^~~~~~~~~~
1 error generated.
make: *** [Makevars:14: tools/px] Error 1
ERROR: compilation failed for package ‘processx’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/processx’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/processx’
Warning in install.packages :
  installation of package ‘processx’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/ps/3jjkc4kj1y98mzlpdm3wp5dm0000gn/T/RtmpNbTlti/downloaded_packages’

Restarting R session...

Loading required package: SeuratObject
Attaching sp
> install.packages("processx")

  There is a binary version available but the source version is later:
         binary source needs_compilation
processx  3.7.0  3.8.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) y
installing the source package ‘processx’

trying URL 'https://cran.rstudio.com/src/contrib/processx_3.8.0.tar.gz'
Content type 'application/x-gzip' length 162539 bytes (158 KB)
==================================================
downloaded 158 KB

* installing *source* package ‘processx’ ...
** package ‘processx’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -Wall -g -O2  -L/usr/local/lib -Wall tools/px.c -o tools/px
tools/px.c:11:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^~~~~~~~~~
1 error generated.
make: *** [Makevars:14: tools/px] Error 1
ERROR: compilation failed for package ‘processx’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/processx’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/processx’
Warning in install.packages :
  installation of package ‘processx’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/ps/3jjkc4kj1y98mzlpdm3wp5dm0000gn/T/RtmpZ6Le4K/downloaded_packages’
