### ISSUE TITLE
process_initialize error 

### ISSUE THREAD

**Issue by pkchouhan14** [r-lib/processx#177]
I wanted to try mlflow. I did install mlflow and loaded it. Got following error

mlflow_log_param("param1", 5)
Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  Command not found

I tried to install mlfow many different ways, as package from Rstudio, git clone and pip install but got same error. 

I have R 3.5.2, Python 3.7.1, Windows 10 pro.

Thank you for helping me in solving this issue.

**Comment by gaborcsardi** [comment]
This just means that processx cannot find the command mlflow is trying to start. So this might be an issue with your mlflow installation. Can you please try to create a reproducible example?

**Comment by gaborcsardi** [comment]
Please reopen with more information if you are still experiencing problems.
