### ISSUE TITLE
Weird result ffmpeg

### ISSUE THREAD

**Issue by muschellij2** [r-lib/processx#183]
Great Package.  I've switched from using `sys` from @jeroen  to run a command line for `ffmpeg`.  It's odd, but with the same set of `args`, I get a corrupted image with `processx` but not `sys`. I understand that the error is fundamentally how `ffmpeg` is creating the object, but it seems as that the real difference occurs as how `processx` runs the command.
<Sorry for updates - wanted to show the gif was in fact intact> 
``` r
library(recordscreen)
tempdir(check = TRUE)
#> [1] "/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//Rtmpd7ikUG"
out = start_screen_record(outfile = tempfile(fileext = ".gif"))
Sys.sleep(4)
res = end_screen_record(out$pid)
stopifnot(file.exists(out$outfile))
magick::image_read(out$outfile)
#> Error in magick_image_readpath(path, density, depth, strip): Magick: CorruptImage `/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/Rtmpd7ikUG/file1506843490e1f.gif' @ error/gif.c/ReadGIFImage/1373

file.remove(out$outfile)
#> [1] TRUE
pid = sys::exec_background("ffmpeg", args = out$args)
Sys.sleep(4)
tools::pskill(pid)
magick::image_read(out$outfile)
```

![](https://i.imgur.com/rxcNVgI.gif)

<sup>Created on 2019-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by gaborcsardi** [comment]
How can I run this. https://github.com/muschellij2/recordscreen/blob/master/DESCRIPTION still uses sys.

**Comment by muschellij2** [comment]
sorry - didn't push and didn't expect such a quick response.  Should work now.  DESCRIPTION has both in there, but processx is the backend for now.

**Comment by gaborcsardi** [comment]
This works:

```r
library(recordscreen)
tempdir(check = TRUE)
#> [1] "/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//Rtmpd7ikUG"
out = start_screen_record(outfile = tempfile(fileext = ".gif"))
Sys.sleep(4)
ps::ps_interrupt(ps::ps_handle(out$pid))
stopifnot(file.exists(out$outfile))
magick::image_read(out$outfile)
```
you `ps_kill()` the process. You can send an interrupt instead with `$interrupt()`.

Also, prefer the methods of the process object, those are safer. E.g. the pid can be reused before you so `ps_handle()` and then you kill the wrong process.

You shouldn't need to use the ps package directly, just use the methods of the process object.

**Comment by gaborcsardi** [comment]
Cool package, btw.!

**Comment by muschellij2** [comment]
Confirmed it works - thanks for the quick response!  I just started on this so thanks for the feedback on `ps`.  Closing
