### ISSUE TITLE
Error while installing on a Centos

### ISSUE THREAD

**Issue by BenAbabaei** [r-lib/processx#188]
Installing package into ‘/gpfs1/homes/uqbababa/.R/library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/processx_3.3.0.tar.gz'
Content type 'application/x-gzip' length 103735 bytes (101 KB)
==================================================
downloaded 101 KB

* installing *source* package ‘processx’ ...
** package ‘processx’ successfully unpacked and MD5 sums checked
** libs
icc -std=gnu99 -g -O2 -std=c99  -Wall tools/px.c -o tools/px
icc -std=gnu99 -g -O2 -std=c99  supervisor/supervisor.c supervisor/utils.c \
      -o supervisor/supervisor
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c init.c -o init.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c poll.c -o poll.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c processx-connection.c -o processx-connection.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c processx-vector.c -o processx-vector.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c create-time.c -o create-time.o
In file included from processx.h(34),
                 from create-time.c(4):
unix/processx-unix.h(32): error: identifier "siginfo_t" is undefined
  void processx__sigchld_callback(int sig, siginfo_t *info, void *ctx);
                                           ^

compilation aborted for create-time.c (code 2)
make: *** [create-time.o] Error 2
ERROR: compilation failed for package ‘processx’
* removing ‘/gpfs1/homes/uqbababa/.R/library/processx’

The downloaded source packages are in
        ‘/gpfs1/scratch/30days/uqbababa/RtmpQeDgXO/downloaded_packages’
Warning message:
In install.packages("processx") :
  installation of package ‘processx’ had non-zero exit status

**Comment by gaborcsardi** [comment]
which os is this exactly?

**Comment by BenAbabaei** [comment]
It's Centos7. I hope that's what you asked about.

**Comment by gaborcsardi** [comment]
Strange, I just compiled it on CentOS 6, with EPEL, without problems.  Anyway, can you try to add 
```
#include <sys/signal.h>
```

at the beginning of `src/unix/processx-unix.h` and then try to install that?

**Comment by gaborcsardi** [comment]
OK, I push a fix, hopefully. Can you try to install that? E.g. 

```r
source("install-github.me/r-lib/processx")
```

**Comment by BenAbabaei** [comment]
I updated INCLUDE_PATH

export INCLUDE_PATH=/usr/include/sys/stat.h:/usr/include/sys/signal.h

then source("https://install-github.me/r-lib/processx")

source("https://install-github.me/r-lib/processx")
Downloading GitHub repo r-lib/processx@master
Running `R CMD build`...
* checking for file ‘/gpfs1/scratch/30days/uqbababa/RtmpysP5N3/remotes40e62dedc91c/r-lib-processx-a8f09d1/DESCRIPTION’ ... OK
* preparing ‘processx’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘processx_3.3.0.9000.tar.gz’
Installing package into ‘/gpfs1/homes/uqbababa/.R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘processx’ ...
** libs
icc -std=gnu99 -g -O2 -std=c99  -Wall tools/px.c -o tools/px
icc -std=gnu99 -g -O2 -std=c99  supervisor/supervisor.c supervisor/utils.c \
      -o supervisor/supervisor
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c init.c -o init.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c poll.c -o poll.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c processx-connection.c -o processx-connection.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c processx-vector.c -o processx-vector.o
icc -std=gnu99 -I/sw/B18a/R/lib64/R/include -DNDEBUG   -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include   -fpic  -g -O2 -std=c99  -c create-time.c -o create-time.o
In file included from processx.h(34),
                 from create-time.c(4):
unix/processx-unix.h(32): error: identifier "siginfo_t" is undefined
  void processx__sigchld_callback(int sig, siginfo_t *info, void *ctx);
                                           ^

compilation aborted for create-time.c (code 2)
make: *** [create-time.o] Error 2
ERROR: compilation failed for package ‘processx’
* removing ‘/gpfs1/homes/uqbababa/.R/library/processx’
Error in i.p(...) :
  (converted from warning) installation of package ‘/30days/uqbababa/RtmpysP5N3/file40e621f13b48/processx_3.3.0.9000.tar.gz’ had non-zero exit status

**Comment by gaborcsardi** [comment]
So where is `siginfo_t` defined on your system?

**Comment by gaborcsardi** [comment]
R itself uses it, so you must have it somewhere...
https://github.com/wch/r-source/blob/c852309a489dc4651b00080624368304b61862f3/src/main/main.c#L492

**Comment by BenAbabaei** [comment]
I cannot find it. I included all the files in '/usr/include/sys' in INCLUDE_PATH. Should I look for it somewhere else?

**Comment by gaborcsardi** [comment]
This is something specific to icc which I don't have access to. For Centos 7 gcc it is included from `sys/signal.h` which is also the standard: https://pubs.opengroup.org/onlinepubs/007904975/basedefs/sys/wait.h.html

Can you please grep your include files to see where `signinfo_t` is defined?

**Comment by gaborcsardi** [comment]
I am not sure that `INCLUDE_PATH` is used by R at all, BTH.

**Comment by BenAbabaei** [comment]
`sys/signal.h` only includes `#include <signal.h>`. May I know how I can search for the place `siginfo_t` is defined? I tried `grep -rl "siginfo_t" /usr/include/` and found a couple of files, but I am not sure what I should look for inside them and how to use these files. We had some problems with other packages which were fixed by including some of .h files into `INCLUDE_PATH`.

**Comment by gaborcsardi** [comment]
> `sys/signal.h` only includes `#include <signal.h>`.

Yeah, but that includes `bits/siginfo.h` where it is defined. Well, conditionally, maybe I would need to define a macro for the right posix standard:
```
#if defined __USE_POSIX199309 || defined __USE_XOPEN_EXTENDED
/* Get the `siginfo_t' type plus the needed symbols.  */
# include <bits/siginfo.h>
#endif
```

**Comment by gaborcsardi** [comment]
Or, maybe icc just does not support the posix standard we need.

**Comment by BenAbabaei** [comment]
Do you mean there is no quick workaround?

**Comment by gaborcsardi** [comment]
which version of icc is this?

**Comment by gaborcsardi** [comment]
Also what is the output of these for you
```
❯ R CMD config CC
clang

❯ R CMD config CFLAGS
-Wall -g -O2

❯ R CMD config CPPFLAGS
-I/usr/local/include
```

**Comment by BenAbabaei** [comment]
I am not sure how I can get the version of rcc I am on!! Sorry.

```
> R CMD config CC
icc -std=gnu99

> R CMD config CFLAGS
-g -O2 -std=c99

> R CMD config CPPFLAGS
-I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/zlib/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/bzip2/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/xz/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/pcre/include -I/gpfs1/groups/rocks/martin/R-roll/BUILD/sdsc-R-3.4.3/curl/include
```

**Comment by gaborcsardi** [comment]
I would try `icc -v` or `icc --version` or checking its manual.

**Comment by BenAbabaei** [comment]
```
icc (ICC) 18.0.2 20180210
```

**Comment by gaborcsardi** [comment]
Can you pls give it another try? I think this should be fixed now.

**Comment by gaborcsardi** [comment]
I am closing this for lack of input. Please reopen if you still have problems.
