### ISSUE TITLE
run() with stdin

### ISSUE THREAD

**Issue by mmuurr** [r-lib/processx#198]
Is it possible to add `stdin` to `run()` (as done with `process$new()` and #27)?

An example where it'd be nice to use `run()`'s built-in synchronous process management is something like calling pandoc where `stdin` is a string and we can capture `stdout` directly into an output string. Ways to do this now include writing some wrapping management around `process$new()` (effectively rewriting some of `run()`'s functionality) or writing the input string to a file and calling pandoc on that file, then deleting the file, which seems clunky.

Either way, thanks much for `processx`; very useful!

**Comment by gaborcsardi** [comment]
Thanks! Yes, this will be added eventually, probably soonish. The critical issue is that in this case it is easy to get deadlocks, and ideally we would need a cross-platform poll() operation that works on writable streams as well. This is super easy for Unix, but a bit cumbersome for Windows, which does not have a poll() system call. In the end it is very similar to how readable streams are polled in processx, but still, it will need some internal changes.

**Comment by gaborcsardi** [comment]
Seems like the `process` docs is wrong and `stdin` is a file name there, not the input string itself. So I guess we could do the same for `run()`.

**Comment by gaborcsardi** [comment]
Actually, now that `run()` forwards extra arguments to `processx$new()`, supplying the `stdin` argument will work nicely. (It should not be `"|"`, that would probably deadlock.)

Example on Unix:
```r
cat(run("cat", stdin = "DESCRIPTION")$stdout)
#> Package: processx
#> Title: Execute and Control System Processes
#> Version: 3.3.1.9000
#> Authors@R: c(
...
```
