### ISSUE TITLE
run() adds quotes, then fails

### ISSUE THREAD

**Issue by peterlittlejohn** [r-lib/processx#204]
Hi,

This packages looks great -- thank you.

Unfortunately I am stumbling on something very basic.
Here's a stripped-down example -- first a working version and then a non-working one:
``$ run("find",c("."),echo_cmd=TRUE) ## works fine``

OUTPUT
Running find .
$status
[1] 0

$stdout
[1] ".\n./fileB\n./fileA\n./fileC\n"

$stderr
[1] ""

$timeout
[1] FALSE

But when I make the expression slightly more complex, it fails:
``$ run("find",c(".","-type f"),echo_cmd=TRUE) ## does not work``

OUTPUT
Running find . **'-type f'**
Error in run("find", c(".", "-type f"), echo_cmd = TRUE) : 
  System command error

The issue seems to be that "type -f" is surrounded by quotes for the submission -- see text in bold above.

As a comparison, this works using system():
``$ system("find . -type f")``

OUTPUT
./fileB
./fileA
./fileC

Running Linux Centos 7 and 
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by gaborcsardi** [comment]
> ```r
> $ run("find",c(".","-type f"),echo_cmd=TRUE) ## does not work
> ```

`-type` and `f` are separate arguments, i.e. you write this as 

```r
run("find", c(".", "-type", "f"), echo_cmd = TRUE) 
```

**Comment by peterlittlejohn** [comment]
Thank you for your prompt reply.  It might be worth mentioning this in the documentation, as one tends to think of "-type -f" as one unit to specify an option for unix commands.
