### ISSUE TITLE
  package ‘processx_3.4.0.tar.gz’ is not available (for R version 3.6.0)

### ISSUE THREAD

**Issue by Shicheng-Guo** [r-lib/processx#210]
Hi All, 

Which R version will be okay for processx_3.4.0? 

  package ‘processx_3.4.0.tar.gz’ is not available (for R version 3.6.0)

Thanks.

**Comment by gaborcsardi** [comment]
R >= 3.2.x is good. I think you probably just saw some temporary trouble with CRAN, or maybe you tried to install Windows binaries, those are not available yet, seemingly: https://cran.rstudio.com/web/packages/processx/

**Comment by gaborcsardi** [comment]
I am closing this, please re-open if it persists.
