### ISSUE TITLE
Webshot function in R gives error

### ISSUE THREAD

**Issue by Osho4U** [r-lib/processx#212]
Hi, I am trying to create image file from Flextable in R. For this I am saving Flextable to htmal and using webshot function and Phantomjs, I am taking screen shot from html file.
I am getting below error when R is executing webshot function:
"Error in supervisor_start() : 
  processx supervisor was not ready after 5 seconds."

Kindly let me know what is the solution for this issue. I am getting this error message when my system got updated last week.
Do we have any other way to create image from Flextable.
Thanks
Rajneesh

**Comment by gaborcsardi** [comment]
`webshot::webshot()` works fine for me, can you please provide more details, e.g. the command you are running, your processx and webshot version and OS?

**Comment by Osho4U** [comment]
Hi, Thanks for your time. I am using windows 7 Service Pack 1 and antivirus is McAfee.
From dataframe, I am creating Flextable. After that I am creating html file by using below command:

htmltools::save_html(htmltools_value(myDataFrame), 'C:/HTML_Files/temp.html')

Once the html file is generated from Flextable, I am using webshot function to generate image file:

webshot::webshot('C:/HTML_Files/temp.html', png_file, vwidth = 1200, vheight = 350, zoom = 2)

here png_file is the full path of the image file which I need to gerenate. It include file name also. This command was working fine till last month. After some update in system, It started giving error.

For Webshot, the version is 0.5.1

and for processx, the version is: 3.4

Thanks
Rajneesh

**Comment by gaborcsardi** [comment]
Hi, can you experiment with it a bit and create a reproducible example? E.g. does the path matter? Does it work for simpler data frames? ETc.

**Comment by gaborcsardi** [comment]
This works fine for me:
```r
library(flextable)

html <- tempfile(fileext = ".html")
png <- tempfile(fileext = ".png")
htmltools::save_html(flextable::htmltools_value(flextable(iris)), html)
webshot::webshot(html, png, vwidth = 1200, vheight = 350, zoom = 2)
shell(png)
```

Latest CRAN flextable, and everything else.

**Comment by Osho4U** [comment]
Hi, Thanks for your time. Sorry, I was late in reply.
I tried your code. The line 
webshot::webshot(html, png, vwidth = 1200, vheight = 350, zoom = 2)

is giving me error:
Error in supervisor_start() : 
  processx supervisor was not ready after 5 seconds.

Thanks
Rajneesh

**Comment by gaborcsardi** [comment]
Can you please include a stack trace via `traceback()`, after the error happens? Maybe you could also debug `phantom_run()` (if that is indeed the function that fails). See `?debug`

**Comment by gaborcsardi** [comment]
I am closing this for lack of input. Please reopen if you still have problems.

**Comment by DRF-TARPA1** [comment]
Error in supervisor_start() : 
  processx supervisor was not ready after 5 seconds.
> traceback()
11: stop("processx supervisor was not ready after 5 seconds.")
10: supervisor_start()
9: supervisor_ensure_running()
8: supervisor_watch_pid(self$get_pid())
7: process_initialize(self, private, command, args, stdout, stderr, 
       cleanup, wd, echo_cmd, supervise, windows_verbatim_args, 
       windows_hide_window, encoding, post_process)
6: .subset2(public_bind_env, "initialize")(...)
5: callr::process$new(phantom_bin, args = args, stdout = "|", stderr = "|", 
       supervise = TRUE)
4: phantom_run(args)
3: (function (url = NULL, file = "webshot.png", vwidth = 992, vheight = 744, 
       cliprect = NULL, selector = NULL, expand = NULL, delay = 0.2, 
       zoom = 1, eval = NULL, debug = FALSE, useragent = NULL) 
   {
       if (is.null(url)) {
           stop("Need url.")
       }
       if (!is.null(cliprect) && !is.list(cliprect)) 
           cliprect <- list(cliprect)
       if (!is.null(selector) && !is.list(selector)) 
           selector <- list(selector)
       if (!is.null(expand) && !is.list(expand)) 
           expand <- list(expand)
       arg_list <- list(url = url, file = file, vwidth = vwidth, 
           vheight = vheight, cliprect = cliprect, selector = selector, 
           expand = expand, delay = delay, zoom = zoom, eval = eval, 
           debug = debug, options = options)
       arg_length <- vapply(arg_list, length, numeric(1))
       max_arg_length <- max(arg_length)
       if (any(!arg_length %in% c(0, 1, max_arg_length))) {
           stop("All arguments should have same length or be single elements or NULL")
       }
       if (length(url) < max_arg_length) 
           url <- rep(url, max_arg_length)
       if (length(url) > 1 && length(file) == 1) {
           file <- vapply(1:length(url), FUN.VALUE = character(1), 
               function(i) {
                   replacement <- sprintf("%03d.\\1", i)
                   gsub("\\.(.{3,4})$", replacement, file)
               })
       }
       if (is_windows()) {
           url <- fix_windows_url(url)
       }
       if (!is.null(cliprect) && !is.null(selector)) {
           stop("Can't specify both cliprect and selector.")
       }
       else if (is.null(selector) && !is.null(cliprect)) {
           cliprect <- lapply(cliprect, function(x) {
               if (is.character(x)) {
                   if (x == "viewport") {
                     x <- c(0, 0, vwidth, vheight)
                   }
                   else {
                     stop("Invalid value for cliprect: ", x)
                   }
               }
               else {
                   if (!is.numeric(x) || length(x) != 4) {
                     stop("'cliprect' must be a 4-element numeric vector or a list of such vectors")
                   }
               }
               x
           })
       }
       if (!is.null(expand)) {
           lengths <- vapply(expand, length, numeric(1))
           if (any(!lengths %in% c(1, 4))) {
               stop("'expand' must be a vector with one or four numbers, or a list of such vectors.")
           }
       }
       optsList <- data.frame(url = url, file = file, vwidth = vwidth, 
           vheight = vheight)
       argToVec <- function(arg) {
           vapply(arg, FUN.VALUE = character(1), function(x) {
               if (is.null(x) || is.na(x)) 
                   NA_character_
               else paste(x, collapse = ",")
           })
       }
       if (!is.null(cliprect)) 
           optsList$cliprect <- argToVec(cliprect)
       if (!is.null(selector)) 
           optsList$selector <- argToVec(selector)
       if (!is.null(expand)) 
           optsList$expand <- argToVec(expand)
       if (!is.null(delay)) 
           optsList$delay <- delay
       if (!is.null(zoom)) 
           optsList$zoom <- zoom
       if (!is.null(eval)) 
           optsList$eval <- eval
       if (!is.null(useragent)) 
           optsList$options <- jsonlite::toJSON(list(pageSettings = list(userAgent = useragent)), 
               auto_unbox = TRUE)
       optsList$debug <- debug
       args <- list("--ignore-ssl-errors=true", system.file("webshot.js", 
           package = "webshot"), jsonlite::toJSON(optsList))
       res <- phantom_run(args)
       if (is.null(res)) 
           return(NULL)
       if (res != 0) {
           stop("webshot.js returned failure value: ", res)
       }
       structure(file, class = "webshot")
   })(url = "U:\\Git\\HAVFI1\\HAVFI1_PRJ2170\\test2_tmpac48eb.html", 
       file = "U:\\Git\\HAVFI1\\HAVFI1_PRJ2170\\test2.jpg")
2: do.call(webshot::webshot, args[ws_args])
1: mapshot(z, file = "test2.jpg")
