### ISSUE TITLE
Occasional NA returned by get_exit_status

### ISSUE THREAD

**Issue by rickhelmus** [r-lib/processx#220]
Hello,

On my Linux box (OpenSUSE) on some occasions the `get_exit_status()` function may return `NA` after execution of a (successful) command. I'm mainly using this function to check if the command executed without problems. I typically notice this when a long batch (~50-100) of commands are executed in chunks, each launched by process$new(). So far it mainly seems when executing Java commands, but this might be coincidence. 

I'm not using `mcparallel` and as far as I can tell none of the dependent packages use `SIGCHLD` handlers. Still I am unsure about this and I was wondering if there would be a way to easily check this. 

Thanks,
Rick

**Comment by hongyuanjia** [comment]
Same issue here. But did not find a easy way to reproduce it.

**Comment by gaborcsardi** [comment]
I am not sure if we can address this without some example that fails.

**Comment by hongyuanjia** [comment]
Agree. Will post a reproducible example once I have.

**Comment by gaborcsardi** [comment]
I will close this now for lack of activity, but please reopen if you have a clue why this would happen.
