### ISSUE TITLE
Error: package or namespace load failed for ‘processx’

### ISSUE THREAD

**Issue by ZihaoXingstudy** [r-lib/processx#221]
Error: package or namespace load failed for ‘processx’:
 .onLoad failed in loadNamespace() for 'processx', details:
  call: ps::ps_handle()
  error: Unknown errorfs_error0NA
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/processx’

**Comment by gaborcsardi** [comment]
Please see https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example and reopen.
