### ISSUE TITLE
webshot::webshot() problems again

### ISSUE THREAD

**Issue by mbojan** [r-lib/processx#222]
This was reported in #212 and I am running into the same problem on Ubuntu 18.04 as a WSL on Windows 10. Reprex:

``` r
fname <- "https://mbojan.github.io/broker_flow/eusn2019.html"
webshot::webshot(fname, "~/Desktop/eusn2019-new.pdf")
#> Error in supervisor_start(): processx supervisor was not ready after 5 seconds.
```

And the `traceback()`:

```
> traceback()
10: stop(cond)
9: throw(new_error("processx supervisor was not ready after 5 seconds."))
8: supervisor_start()
7: supervisor_ensure_running()
6: supervisor_watch_pid(self$get_pid())
5: process_initialize(self, private, command, args, stdin, stdout,
       stderr, pty, pty_options, connections, poll_connection, env,
    ...
4: .subset2(public_bind_env, "initialize")(...)
3: callr::process$new(phantom_bin, args = args, stdout = "|", stderr = "|",
       supervise = TRUE)
2: phantom_run(args)
1: webshot::webshot(fname, "~/Desktop/eusn2019-new.pdf")
```

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Ubuntu 18.04.3 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       localtime                   
#>  date     2019-09-19                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  callr         3.3.1   2019-07-18 [1] CRAN (R 3.6.1)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.2.0   2019-09-07 [1] CRAN (R 3.6.1)
#>  digest        0.6.20  2019-07-04 [1] CRAN (R 3.6.0)
#>  DT            0.9     2019-09-17 [1] CRAN (R 3.6.1)
#>  ellipsis      0.2.0.1 2019-07-02 [1] CRAN (R 3.6.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
#>  htmlwidgets   1.3     2018-09-30 [1] CRAN (R 3.6.0)
#>  jsonlite      1.6     2018-12-07 [1] CRAN (R 3.6.0)
#>  knitr         1.25    2019-09-18 [1] CRAN (R 3.6.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.5   2019-08-26 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.6.1)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.0)
#>  rmarkdown     1.15    2019-08-21 [1] CRAN (R 3.6.1)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.2.1   2019-07-25 [1] CRAN (R 3.6.1)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.0)
#>  webshot       0.5.1   2018-09-28 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.9     2019-08-21 [1] CRAN (R 3.6.1)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#> 
#> [1] /home/mbojan/R/library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by mbojan** [comment]
Interestingly, running (mind the file name instead of a full path to output file in the JSON)

```bash
phantomjs --ignore-ssl-errors=true ~/R/library/3.6/webshot/webshot.js '[{"url":"https://mbojan.github.io/broker_flow/eusn2019.html","file":"eusn2019-new.pdf","vwidth":992,"vheight":744,"delay":0.2,"zoom":1,"debug":false}]'
```

works. However,

```r
fname <- "https://mbojan.github.io/broker_flow/eusn2019.html"
webshot::webshot(fname, "output.pdf")
```

still fails.

**Comment by mbojan** [comment]
I have

```
$ phantomjs --version
2.1.1
```

LMK if I can debug this further.

**Comment by dgodderis** [comment]
I have the same problems as mbojan above. When trying to use it in a docker container based on rocker/tidyverse, both webshot and webshot2 fail.

**Comment by dgodderis** [comment]
Other functions have the same issues with `process$new`: 

`p <- process$new("sleep", "2", supervise=TRUE)
Error in supervisor_start() :
  processx supervisor was not ready after 5 seconds.`

**Comment by dgodderis** [comment]
@mbojan to continue my application for now, I edited an internal function of webshot so it does not use the supervise argument of processx:

```
    p <- callr::process$new(
      phantom_bin,
      args = args,
      stdout = "|", stderr = "|",
      supervise = FALSE
    )
```
I edited this in the the `phantom_run()`-function of webshot with `assignInNamespace()`. I know it's not good practice, but at least I can continue development.

**Comment by mbojan** [comment]
> @mbojan to continue my application for now, I edited an internal function of webshot so it does not use the supervise argument of processx:
> 
> ```
>     p <- callr::process$new(
>       phantom_bin,
>       args = args,
>       stdout = "|", stderr = "|",
>       supervise = FALSE
>     )
> ```

Thanks @dgodderis ! That's help full. Although I need  a "one shot `webshot()`" I'll cookup a patched copy for future uses.


> I edited this in the the `phantom_run()`-function of webshot with `assignInNamespace()`. I know it's not good practice, but at least I can continue development.

That's actually a great practice for private purposes. It is only a little bit inferior to forking the original and applying the change on a branch... ;)

Thanks again!

**Comment by gaborcsardi** [comment]
I just downloaded `rocker/tidyverse` and 
```r
p <- process$new("sleep", "2", supervise=TRUE) 
```
works fine in the RStudio server. webshot works as well, although I had to install bzip2 in the container first, and then call `webshot::install_phantomjs()`.

Apart from these I haven't changed anything on the container. 

So if this still fails for you, can you please provide a reproducible example? Thanks.

**Comment by mbojan** [comment]
@gaborcsardi reproducible example is in the issue description.

**Comment by gaborcsardi** [comment]
Well, that's pretty hard to reproduce for me, as I don't have Windows 10 with WSL, but @dgodderis said he had similar failures in a Docker container, which should be much easier to reproduce.

**Comment by mbojan** [comment]
Does my example work for you in a Docker?

**Comment by gaborcsardi** [comment]
webshot does not seem to resolve `~` but apart from that, yes, it does work.

**Comment by mbojan** [comment]
OK thanks, that means something, It does not work for me even without the `~`... I'll try to poke some more.

**Comment by dgodderis** [comment]
I've dug a bit deeper:
- the reason webshot and webshot2 didn't work in rocker/tidyverse had something to do with networking issues (ports) of `appshot()`, processx worked as expected (my bad for misinformation).
- when developing in Windows10, WSL, `webshot()` immediately fails on `processx supervisor was not ready after 5 seconds.`. I could only replicate this in WSL.

So unfortunately I'm not able to give a reproducible example :/

**Comment by gaborcsardi** [comment]
@dgodderis Thanks, it seems that WSL is problematic then. I'll have to take a look....

**Comment by gaborcsardi** [comment]
Finally managed to get a Windows laptop with WSL, and I can repro this, so it'll be probably fixed soon.

**Comment by gaborcsardi** [comment]
Some more info:

```
debug: p <- process$new(supervisor_path(), args = c("-p", Sys.getpid(),
    "-i", supervisor_info$stdin_file), stdout = "|", cleanup = FALSE)
Browse[2]> supervisor_path()
[1] "/home/csardi/R/x86_64-pc-linux-gnu-library/3.4/processx/bin/supervisor"
Browse[2]> Sys.getpid()
[1] 20
Browse[2]> n
debug: ready <- FALSE
Browse[2]> p
PROCESS 'supervisor', finished.
Browse[2]> p$read_all_ou
p$read_all_ou
Browse[2]> p$read_all_output()
[1] "PID: 156\nfopen.\nfopened.\nReady\nError setting up signal handler.\n"
```
