### ISSUE TITLE
Spinner not showing up

### ISSUE THREAD

**Issue by hugomflavio** [r-lib/processx#223]
Hi,

I am running R GUI version 3.6.0 on Windows 10. While my problem stems from trying to use callr::r() with the spinner, I have tracked the problem down to  [the spin() function](https://github.com/r-lib/processx/blob/88437067f84bc27b3d01da05bfdf3714f33d9689/R/run.R#L278), defined inside the function run_manage().

As an example, running the code below (from the demo code in the readme) will not produce a spinner.

```r
px <- paste0(
  system.file(package = "processx", "bin", "px"),
  system.file(package = "processx", "bin", .Platform$r_arch, "px.exe")
)

result <- run(px,
  c("out", "  foo",
    "sleep", "1",
    "out", "\r  bar",
	"sleep", "1",
	"out", "\rX foobar\n"),
  echo = TRUE, spinner = TRUE)
```

I have explored the run_manage function and I found that editing the spin function from:
```r
# Currently defined spin
  spin <- (function() {
    state <- 1L
    phases <- c("-", "\\", "|", "-")
    function() {
      cat("\r", phases[state], "\r", sep = "")
      state <<- (state + 1) %% length(phases) + 1L
    }
  })()
```
to:
```r
# spin function edited by me
spin <- (function() {
  state <- 1L
  phases <- c("-", "\\", "|", "/")
  function() {
    cat("\r", phases[state], "\r", sep = "")
    state <<- (state)%%length(phases) + 1L
    flush.console() 
  }
})()
```
solves the issue. 

Specifically, adding the flush.console() line solves the issue: the spinner shows up and rolls in place as expected.

I took the chance to fix an additional issue where the spinner phases were not showing up in the correct order, by changing the lines starting with "phases <- ..." "state <<- ..." (see above).

This is the first time I am posting an issue in someone's repository, so I hope I am not breaking any formality (apologies if I am).

Thanks for any help you can give me!
Hugo

**Comment by gaborcsardi** [comment]
Thanks! I think you are right, do you want to submit a pull request?
