### ISSUE TITLE
Equivalent to system2(input=*)

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/processx#227]
Apologies if this is mentioned in the docs but I couldn't find it.

Does `process` and/or `run` have an equivalent to the `input` argument of `base::system2`? This lets you pipe some text to the standard input of the process. `run(stdin=*)` lets you specify a filename, which isn't the same thing.

**Comment by gaborcsardi** [comment]
If you want to write to the stdin of the process from the R session:
```r
❯ p <- processx::process$new("cat", stdin = "|", stdout = "|")
❯ p$write_input("foobar\n")
❯ p$read_output()
[1] "foobar\n"

❯ p$write_input("foobar again\n")
❯ p$read_output()
[1] "foobar again\n"

❯ p$kill()
[1] TRUE
```

**Comment by Hong-Revo** [comment]
Thanks, maybe I just don't understand the processx model, but it doesn't seem to be working. The scenario is that I'm trying to log into an Azure docker registry, and specifying the password via stdin. The command is

```
docker login --username <me> --password-stdin
```

`system2(*, input="<password>")` works, and on RTFsource, I could see that it's simply writing the password to a tempfile and passing the filename to the `stdin` argument. Indeed, if I use the same trick with `processx::run`, it also works. But I can't seem to get the `processx::process` code posted above to work; when I try to do anything with docker, it fails with "unauthorized: authentication required". It would be nice to get away from having a tempfile, although it's probably not super-serious.

**Comment by Hong-Revo** [comment]
Specific commands:

```r
p <- processx::process$new("docker",
    c("login", "--username", "<username>", "--password-stdin", "hongsacr.docker.io"),
    stdin="|")
p$write_input("<password>")
p$kill()
p
# PROCESS 'docker', finished.
```

```
C:\Users\hongo>docker push hongsacr.azurecr.io/hello-world
The push refers to repository [hongsacr.azurecr.io/hello-world]
d672ddd9eebb: Preparing
5fceba303ee3: Preparing
256a7af3acb1: Preparing
unauthorized: authentication required
```

**Comment by gaborcsardi** [comment]
It goes like this:

```r
p <- processx::process$new(
  "docker", 
  c("login", "-u", "gaborcsardi", "--password-stdin"), 
  stdin = "|", stdout = "|", stderr = "|")
p$write_input("<password>")
close(p$get_input_connection())
p$wait()
p$read_all_output()
p$read_all_error()
p$get_exit_status()
```

`docker` waits for the end of the stdin, so you need to close it. Also, no need to include a newline, just the password.

You might want to use a timeout in `p$wait()`, not to wait indefinitely.

It is quite detailed, but the `process` class was designed to give you full control.

**Comment by Hong-Revo** [comment]
Thanks!
