### ISSUE TITLE
Pipe

### ISSUE THREAD

**Issue by peterlittlejohn** [r-lib/processx#233]
Hello,

I am trying to execute a number of unix commands, all piped.

Here's a basic example that gets to the gist of what I am trying to do: a zcat in the first example, followed by a zcat, then a head in the second.  del.csv is a file with one word, "hello".

Example 1 ## works
```
> a <- run("zcat",c("del.csv.gz"),echo_cmd=TRUE)
Running zcat del.csv.gz
> a
$status
[1] 0

$stdout
[1] "hello\n"

$stderr
[1] ""

$timeout
[1] FALSE

```
Example 2 ## fails
```
> a <- run("zcat",c("del.csv.gz","|","head"),echo_cmd=TRUE)
Running zcat del.csv.gz '|' head ## this shows why it will fail...the pipe has quotes
Error in run("zcat", c("del.csv.gz", "|", "head"), echo_cmd = TRUE) : 
  System command error

```
Am I misspecifying something?  Or is processx not meant to be used for complex/piped unix expressions?

**Comment by gaborcsardi** [comment]
The `|` notation is for the shell, and not for the OS. If you want to use it, you need to start a shell, e.g. `sh` or `bash`. This will probably make your code less portable, if that's an issue for you. E.g.

```r
❯ run("sh", c("-c", "seq 1 10 | head -n 4"), echo = TRUE)
1
2
3
4
$status
[1] 0

$stdout
[1] "1\n2\n3\n4\n"

$stderr
[1] ""

$timeout
[1] FALSE
```

**Comment by peterlittlejohn** [comment]
Ah yes! Thank you for your prompt reply.
