### ISSUE TITLE
Error while shutting down parallel: unable to terminate some child processes

### ISSUE THREAD

**Issue by kforner** [r-lib/processx#236]
As discussed in #113, there seems to be an interaction between `parallel::mclapply` and `processx` related to a signal handler. 

The symptom is this message when leaving a R session or entering debug:
`Error while shutting down parallel: unable to terminate some child processes`

It also comes with a noticeable delay to quit or enter the debug session. 

I could not manage to build a reproducible example yet.
And actually I do not use **processx** directly but **callr**.

**Comment by gaborcsardi** [comment]
Here is a reprex:
```r
# Save this into a file and run it from the command line as
# R --no-save -q < <filename>

library(parallel)

# Create cluster, check that it works
cl <- parallel::makeForkCluster(2)
mclapply(1:2, function(x) x)

# Double check that subprocesses are running
ps::ps_children(ps::ps_handle())

# Run a parallel background job
job <- mcparallel(Sys.sleep(1))

# Start processx process, it will overwrite the signal handler
processx::run("true")

# Wait for parallel job to finish
mccollect(job)

# Quit, this will hang a big, and then quit with a message,
# but otherwise a zero (=successful) exit status
```

**Comment by gaborcsardi** [comment]
@kforner can you pls try #237?

For now this is opt-in and you need to set the `PROCESSX_NOTIFY_OLD_SIGCHLD` env var to some non-empty value, before processx is loaded. It seems that it is ok to notify parallel's signal handler, even after the parallel cluster has stopped, which is good. 

It is surely not OK to _unload_ parallel, though, that's a crash for sure. FYI.

**Comment by kforner** [comment]
great ! I confirm it exhibits the same behavior I'm getting.

**Comment by gaborcsardi** [comment]
Wait, so does this PR fix the issue for you?

**Comment by gaborcsardi** [comment]
Oh, you mean the reprex works? That's good. Can you pls try the PR? Thanks!

**Comment by kforner** [comment]
the PR seems to work pretty well! 
It fixes your reprex, and also one of my non-minimal use cases. 
I will use from now by default and tell you if I see any side-effects.

Thanks a lot !
P.S: Do you plan to merge it soon or should I use this branch ?

**Comment by gaborcsardi** [comment]
Yes, I'll merge it today, and a new release also coming this week.

**Comment by gaborcsardi** [comment]
Btw. I want to document this somewhere. Where would you look for documentation like this? Maybe a FAQ would be appropriate?

**Comment by kforner** [comment]
good question... Yes a FAQ at the r-lib level. 
Maybe also mention it in processx/callr/rcmdcheck package synopsis (or main function doc).
Anyway, people will search for the error message and end up on posts as this one. 
You could conclude this issue by the link on the FAQ ?

**Comment by gaborcsardi** [comment]
Good idea, but we don't really have an r-lib level FAQ, and it is not clear where that would go. So for now, I just put it in the README.

**Comment by mschubert** [comment]
To avoid confusion (and as I misunderstood), maybe this helps someone who lands here in the future:

Reacting to the environment variable `PROCESSX_NOTIFY_OLD_SIGCHLD` has been merged and works, but (June 2020) this setting is **not default and needs to be set explicitly** to the shutdown lag/error message.
