### ISSUE TITLE
run hangs with mpiexec

### ISSUE THREAD

**Issue by bbbales2** [r-lib/processx#239]
On Ubuntu 18.04 with OpenMPI (just the default configuration installed from the package manager), I can run this command from the command line:

```
:/$ mpiexec ls
bin    dev   initrd.img      lib32	 media	proc  sbin  sys  var
boot   etc   initrd.img.old  lib64	 mnt	root  snap  tmp  vmlinuz
...
```

However if I run the same thing in processx it hangs after executing the command (it never returns control to R):

```
processx::run(command = "mpiexec", args = "ls", echo = TRUE)
```

If I run this with process$new I can check is_alive and it stays TRUE.

I can run this with system and it executes and returns control:

```
system("mpiexec ls")
```

Any ideas about what might be happening? I'm not entirely sure how this works, and since mpiexec is forking processes to run in parallel it seems reasonable that it might be messing something up so processx isn't able to detect what is going on. Any tips would be appreciated!

**Comment by gaborcsardi** [comment]
My guess would be that `mpiexec` needs a terminal or behaves differently if there is no controlling terminal?

Try to run it in the background, and read out its output, i.e. something like

```r
pr <- process$new("mpiexec", "ls", echo = TRUE, stdout = "|", stderr = "|")
pr$read_output()
pr$read_error()
```

**Comment by bbbales2** [comment]
Still doesn't work. I do that and then check ```pr$is_alive()``` long after I've gotten the output back and it still stays alive (and I can see the process with ```ps``` in the terminal).

I switch to mpich instead of OpenMPI (these are two alternate implementations of the mpi library), and it seems to work fine now.

Any other ideas? I can make an issue with OpenMPI if it seems like something that is getting messed up on their end.

**Comment by gaborcsardi** [comment]
My guess is still that `mpiexec` behaves differently if there is no terminal, like in processx. You can try to use a pseudo-terminal, this only works on Unix though, IDK if you need Windows support. E.g. this works for me:

```r
pr <- process$new("mpiexec", c("--allow-run-as-root", "ls"), pty = TRUE)
pr$wait()
pr$read_output()
#> [1] "works\r\nworks\r\n"
```

But actually this works as well, maybe because my cluster is local:

```r
processx::run("mpiexec", c("--allow-run-as-root", "ls"))
#> $status
#> [1] 0
#> 
#> $stdout
#> [1] "works\nworks\n"
#> 
#> $stderr
#> [1] ""
#> 
#> $timeout
#> [1] FALSE
```

**Comment by yizhang-yiz** [comment]
I can confirm it works on remote cluster too:
```r
processx::run("mpiexec", c("-l", "-f", "hosts", "hostname"))
$status
[1] 0

$stdout
[1] "[0] ip-10-128-17-227\n[1] ip-10-128-3-249\n"

$stderr
[1] ""

$timeout
[1] FALSE
```

**Comment by gaborcsardi** [comment]
Without a reproducible example, I can't do much here. E.g. it would be nice to see it in a container.

**Comment by bbbales2** [comment]
Makes sense
