### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rgunaratna** [r-lib/processx#248]
Hi,
I was trying to install devtools when a processx compilation error occurred. I tried install.packags() but didn't fix the issue. I'd really appreciate any workaround. Please find the sessionInfo() below.

Best,
Ramesh

Makevars file has the following line since processx gave c99 error earlier.
CC = gcc -std=c99

> install.packages("processx", lib="/home/xxxxx/R/x86_64-redhat-linux-gnu-library/3.6")
trying URL 'https://mirrors.nics.utk.edu/cran/src/contrib/processx_3.4.2.tar.gz'
Content type 'application/x-gzip' length 130148 bytes (127 KB)
==================================================
downloaded 127 KB

* installing *source* package 'processx' ...
** package 'processx' successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -std=c99 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -Wall tools/px.c -o tools/px
gcc -std=c99 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  supervisor/supervisor.c supervisor/utils.c \
      -o supervisor/supervisor
supervisor/supervisor.c: In function 'sleep_ms':
supervisor/supervisor.c:91:5: warning: implicit declaration of function 'usleep' [-Wimplicit-function-declaration]
     usleep(milliseconds * 1000);
     ^
supervisor/supervisor.c: In function 'pid_is_running':
supervisor/supervisor.c:134:5: warning: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
     int res = kill(pid, 0);
     ^
supervisor/supervisor.c: In function 'main':
supervisor/supervisor.c:332:5: warning: implicit declaration of function 'fileno' [-Wimplicit-function-declaration]
     if (fcntl(fileno(fp_input), F_SETFL, O_NONBLOCK) == -1) {
     ^
supervisor/supervisor.c:351:22: error: storage size of 'sa' isn't known
     struct sigaction sa;
                      ^
supervisor/supervisor.c:353:5: warning: implicit declaration of function 'sigemptyset' [-Wimplicit-function-declaration]
     sigemptyset(&sa.sa_mask);
     ^
supervisor/supervisor.c:354:5: warning: implicit declaration of function 'sigaction' [-Wimplicit-function-declaration]
     if (sigaction(SIGINT, &sa, NULL)  == -1 ||
     ^
supervisor/supervisor.c:351:22: warning: unused variable 'sa' [-Wunused-variable]
     struct sigaction sa;
                      ^
make: *** [supervisor/supervisor] Error 1
ERROR: compilation failed for package 'processx'
* removing '/home/rameshg/R/x86_64-redhat-linux-gnu-library/3.6/processx'

The downloaded source packages are in
	'/tmp/RtmpcIjUX7/downloaded_packages'
Warning message:
In install.packages("processx", lib = "/home/rameshg/R/x86_64-redhat-linux-gnu-library/3.6") :
  installation of package 'processx' had non-zero exit status
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Springdale Linux 7.7 (Verona)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2

**Comment by rgunaratna** [comment]
My bad.. I was able to fix this by adding CFLAGS=-std=gnu11 (#fix 136) to the Makevars file.

**Comment by gaborcsardi** [comment]
Hmmm, should we add that flag? Or should we only add it on Linux or RedHat? Do you need it for other packages as well?

**Comment by rgunaratna** [comment]
I encountered only this one. Might not be a bad idea to give this as an option, if possible.
