### ISSUE TITLE
Converting a commandline string into processx::run args

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/processx#251]
Often, it's easier/more intuitive to provide the input options to a program as a full string:

    --arg1 --arg2 "here is a sentence" "/path/to/file with spaces"

However, processx expects each option to be a separate element in a vector of strings:

    c("--arg1", "--arg2", "here is a sentence", "/path/to/file with spaces")

Is there a good/recommended way of going from the first to the second? Simply using `strsplit` to split on spaces will fail on the input here, since it will also break up the inputs that have spaces in them.

**Comment by gaborcsardi** [comment]
Unfortunately this is a difficult problem and the procedure is different depending on which shell the command line was for. E.g. in Unix single quotes are special, on Windows they are not. In Windows backticks are special, in Unix they are special in a different way. Different Unix shells also have different quoting rules. 

This is exactly why it is much simpler to use the second form, which has no such ambiguities.

**Comment by gaborcsardi** [comment]
It is unlikely that we could implement this in a ways that is actually useful, so I am closing this.
