### ISSUE TITLE
Cannot pipe to a file from processx::run()

### ISSUE THREAD

**Issue by jameslamb** [r-lib/processx#254]
Thanks for this awesome project! We're starting to use it in [LightGBM](https://github.com/microsoft/LightGBM) to get around the overhead introduced by `system()` and `system2()`.

In the docs for `?processx::run`, I see this:

> ...	
Extra arguments are passed to process$new(), see process.

In `?procesxx::process`, I see the argument `stdout`, with this description:

> What to do with the standard output. Possible values: NULL: discard it; a string, redirect it to this file; "|": create a connection for it.

Given that, I expected to be able pass `stdout` as a keyword argument to get `processx::run()` to write to a file.

```r
processx::run(
    command = "ls"
    , stdout = "file.txt"
)
```

This doesn't work, though. It results in the following error:

> Error in processx::run(command = "ls", stdout = "file.txt") : 
  argument 2 matches multiple formal arguments

I think this is because of fuzzy argument name matching in R. `stdout` is being matched to all of the `stdout_*` arguments in `processx::run()`.

Is there another way to get `processx::run()` to pipe stdout to a file? If not I'll drop down to the `process` object. Thanks!

**Comment by gaborcsardi** [comment]
Yes, that does not work. Even if you could pass `stdout` through, it would probably not work because `run()` sets that argument itself.

I think you have two options, either use `stdout_callback` or use `process$new()` directly. The latter is probably better. E.g. if you just want to start the process and wait for it, you can:

```r
p <- processx::process$new("ls", stdout = "file.txt")
p$wait()
```

**Comment by jameslamb** [comment]
Ah ok, makes sense. I think it might be valuable to explicitly list the possible arguments that can be passed into `...` if only  subset of the arguments to `process$new()` will work.

You can close this issue. Thanks again for the great project and the quick response!
