### ISSUE TITLE
ps methods test often fails on Ubuntu automated test infrastructure

### ISSUE THREAD

**Issue by ginggs** [r-lib/processx#258]
Hi

The ps methods test often fails on Ubuntu automated test infrastructure.
It fails most often on the s390x architecture [1], which happens to be big-endian, but sometimes also on ppc64el [2] and amd64 [3].

I've tried to reproduce the failure locally without success.

Do you have any ideas on how I can debug this issue, or how to make this test more robust?

Thanks
Graham

[1] http://autopkgtest.ubuntu.com/packages/r/r-cran-processx/groovy/s390x
[2] http://autopkgtest.ubuntu.com/packages/r/r-cran-processx/groovy/ppc64el
[3] http://autopkgtest.ubuntu.com/packages/r/r-cran-processx/groovy/amd64

```
> library(testthat)
> library(processx)
> 
> Sys.setenv("R_TESTS" = "")
> 
> test_check("processx", reporter = "summary")
assertions: ........................................................................................................................................................................
character IO: ...........
Cleanup: ..
client-lib: ............................................................
Connections: ........
environment: ..
errors.R: .....................................................S.................SS...SSSS..
errors: ..........
extra connections: SSS
io: ..................S..........
kill_tree: SSSSSS.S
polling connections: .........
poll-curl: SSS
poll stress test: S
poll: ................
poll multiple processes: ......................................................................................................
poll connection: .........
print: ..
process: ..........
ps methods: .1
pty: SSSS
run: ......................................................................S.
set std streams: ............................
SIGCHLD handler interference: SSSSSSSS
stdin: SSSSSS
stress test: SSS
utils: SS..........................................
waiting on processes: S.......S

== Skipped =====================================================================
```
...
```
== Failed ======================================================================
-- 1. Error: ps methods (@test-ps-methods.R#13)  -------------------------------
No such process, pid 2625, ???
Backtrace:
 1. testthat::expect_true(ps::ps_name(ps) %in% c("px", "px.exe")) test-ps-methods.R:13:2
 5. ps::ps_name(ps)

== DONE ========================================================================
```

**Comment by gaborcsardi** [comment]
This is from here: https://github.com/r-lib/processx/blob/2550adccf8abf9d347e596edb7f83288b5ce3512/tests/testthat/test-ps-methods.R#L13

Why it fails, I am not sure. Some wild guesses:
- the process is not initialized properly yet when `ps_name()` is called. IDK if this is possible at all.
- the process failed to start for some reason. Too many processes on the system?
- something is wrong with the process start time stamp, that's why we can't find the process?

Maybe you can just run this interactively, in a loop until it fails? I am happy to help if you can give me some (temporary) access to s390x.

**Comment by ginggs** [comment]
Thanks for your suggestions.

I was hoping to come back with some definitive answers, but no luck so far. :(

I don't know where one can easily get access to s390x, but I don't think this a problem with that architecture, as it does fail elsewhere too.

So far, I've found that by adding `Sys.sleep(50)` as below, the test would pass more often (but still not every time) on s390x.  To me, this suggests something in line with your first guess.  However, the test then started to fail more often on amd64, so I am at a loss.
```
   ps <- p$as_ps_handle()
   expect_s3_class(ps, "ps_handle")
+  Sys.sleep(50)
   expect_true(ps::ps_name(ps) %in% c("px", "px.exe"))
```

I also tried forcing `process$new()` to fail, as below.  This made the test always fail, however with the same `No such process, pid nnnn, ???` failure as before, so it seems it is not possible to tell whether spawning `sleep` was successful or not.
```
   px <- get_tool("px")
-  p <- process$new(px, c("sleep", "100"))
+  p <- process$new(px, c("non-existent", "100"))
   on.exit(p$kill(), add = TRUE)
```

**Comment by gaborcsardi** [comment]
One thing we can do is checking that the process is up. If it is up, then it is probably my 3rd guess. If it is not up, then probably the 2nd. Can you try adding this before the first `expect_true()`?

```r
if (!p$is_alive()) return()
```

**Comment by gaborcsardi** [comment]
Btw. amd64 is just x86-64, right?

**Comment by ginggs** [comment]
I'll give that a try, thanks.

Yes, amd64 = x86_64.

**Comment by gaborcsardi** [comment]
I installed ppc64el in qemu, but cannot repro this, and I cannot repro on amd64 either.

**Comment by ginggs** [comment]
Now with only:
```
   ps <- p$as_ps_handle()
   expect_s3_class(ps, "ps_handle")
+  if (!p$is_alive()) return()
   expect_true(ps::ps_name(ps) %in% c("px", "px.exe"))
```
I got 3 of 6 failures on amd64 and 6 of 6 failures on s390x.

**Comment by gaborcsardi** [comment]
Interesting. So the process is definitely running. I wonder why I cannot reproduce this in my s390x qemu VM.

Can you try to add these lines after the `expect_s3_class` line?

```r
old <- options(digits = 22)
on.exit(options(old), add = TRUE)
print(as.numeric(ps::ps_create_time(ps::ps_handle(p$get_pid()))))
print(p$.__enclos_env__$private$starttime)
expect_identical(
  as.numeric(ps::ps_create_time(ps::ps_handle(p$get_pid()))),
  p$.__enclos_env__$private$starttime
)
```

The two numbers should match exactly.

**Comment by ginggs** [comment]
This time I got 5 of 6 failures on amd64 and 5 of 6 failures on s390x.

The failures all looked the same:
```
== Failed ======================================================================
-- 1. Failure: ps methods (@test-ps-methods.R#17)  -----------------------------
as.numeric(ps::ps_create_time(ps::ps_handle(p$get_pid()))) not identical to p$.__enclos_env__$private$starttime.
Objects equal but not identical

-- 2. Error: ps methods (@test-ps-methods.R#21)  -------------------------------
No such process, pid 2381, ???
Backtrace:
 1. testthat::expect_true(ps::ps_name(ps) %in% c("px", "px.exe")) test-ps-methods.R:21:2
 5. ps::ps_name(ps)
```

**Comment by gaborcsardi** [comment]
OK, I think I can fix this.

**Comment by gaborcsardi** [comment]
Can you pls also show the printed time stamps? They should be number in the middle of the sea of dots that the tests print.

**Comment by ginggs** [comment]
s390x fail:
```
ps methods: .[1] 1593774473.859999895096
[1] 1593774474.859999895096
12
```

s390x pass:
```
ps methods: .[1] 1593774495.859999895096
[1] 1593774495.859999895096
..............
```

s390x fail:
```
ps methods: .[1] 1593774492.869999885559
[1] 1593774493.869999885559
12
```

amd64 pass:
```
ps methods: .[1] 1593774569.910000085831
[1] 1593774569.910000085831
..............
```

amd64 fail:
```
ps methods: .[1] 1593774591.930000066757
[1] 1593774590.930000066757
12
```

amd64 fail:
```
ps methods: .[1] 1593774728.369999885559
[1] 1593774727.369999885559
12
```

**Comment by gaborcsardi** [comment]
If I fix this in processx, how can you test it? Should I push it to a branch? Or send you a patch to the package? Or a package .tar.gz?

**Comment by ginggs** [comment]
Whichever is easiest for you.  Push to a branch, or a patch, are easy for me.

**Comment by gaborcsardi** [comment]
See here: https://github.com/r-lib/processx/tree/fix/start-time-ps
Of course I am not sure if this fixes it. If it does not, then we'll need to do some more debugging.

**Comment by ginggs** [comment]
3 of 6 failures on amd64 and 6 of 6 failures on s390x.

**Comment by gaborcsardi** [comment]
The same way, I assume, with 1s difference?

**Comment by gaborcsardi** [comment]
Btw. are these logs also available online? They don't seem to be at http://autopkgtest.ubuntu.com/packages/r/r-cran-processx

**Comment by ginggs** [comment]
> The same way, I assume, with 1s difference?

Sorry, my last tests did not include the debugging `print()` statements. :-(

> Btw. are these logs also available online?

They are, but testing in my PPA [1], not the Ubuntu archive, so a little convoluted to see them.

Here are my recent results:

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy-ginggs-testing/?format=plain

e.g. the log for my most recent s390x result is:

groovy/s390x/r/r-cran-processx/20200703_172956_a54fe@/log.gz

append that to:

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy-ginggs-testing/

and you get the log:

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy-ginggs-testing/groovy/s390x/r/r-cran-processx/20200703_172956_a54fe@/log.gz



[1] https://wiki.ubuntu.com/ProposedMigration#Testing_against_a_PPA

**Comment by ginggs** [comment]
I added the code to print the timestamps again.
Yes, still the one second difference.

amd64 fail:
```
ps methods: .[1] 1593847846.52999997139
[1] 1593847845.52999997139
12
```

amd64 pass:
```
ps methods: .[1] 1593847844.599999904633
[1] 1593847844.599999904633
..............
```

s390x fail:
```
ps methods: .[1] 1593847773.27999997139
[1] 1593847774.27999997139
12
```

**Comment by gaborcsardi** [comment]
Thanks for bearing with me! I have just pushed a commit to the same debug branch, that prints out some debug info, hopefully this will help us see what is wrong. You don't need to add any print statements, but try to build this please. Thanks!

**Comment by ginggs** [comment]
amd64 pass:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy-ginggs-testing/groovy/amd64/r/r-cran-processx/20200704_105208_4f386@/log.gz

amd64 fail:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy-ginggs-testing/groovy/amd64/r/r-cran-processx/20200704_105226_e95f9@/log.gz

s390x pass:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy-ginggs-testing/groovy/s390x/r/r-cran-processx/20200704_110033_89eb9@/log.gz

It passed 6 of 6 times on s390x so far.  Do you need me to run it a few more times to get a fail here?

**Comment by gaborcsardi** [comment]
Thanks! Hopefully the amd64 fail will be enough to figure it out, I'll look at it later today.

**Comment by gaborcsardi** [comment]
It seems that processx is correct, and ps is off by one, unfortunately. Can you also run the processx tests with the dev version of ps? I.e. the one from https://github.com/r-lib/ps? I have just pushed a change to that that hopefully will fix this.

**Comment by gaborcsardi** [comment]
Btw. do you think get the exact type of these machines? E.g. the output of 

```
uname -a
cat /proc/cpuinfo
```

Thanks!

**Comment by gaborcsardi** [comment]
Actually, my ps fix is most probably wrong, so no rush just yet. :(

**Comment by gaborcsardi** [comment]
OK, I think I got it, it is this: https://github.com/giampaolo/psutil/issues/1724 
It seems that in a container, but maybe also on the iron, the kernel boot time can change. This is not a problem for ps, because it cached the boot time. But processx does not use ps's cache, it queries the boot time for itself, and sometime it will get a different value. 

I can easily work around this in processx.

**Comment by ginggs** [comment]
Great!  Let me know when you have something for me to test.

**Comment by gaborcsardi** [comment]
Can you please try the `fix/start-time-ps` branch now? (Force-pushed, sorry if this causes trouble.) I am fairly confident that this will fix it.

It seems like this happens more often in Docker, you probably use Docker for amd64. It may have also happened if the machine has a clock skew and the RTC time is often adjusted.

**Comment by ginggs** [comment]
I think you've got it!  6 of 6 passes on amd64 and 6 of 6 passes on s390x.

There was a delay earlier and I had to wait for my built package to be published before I could schedule tests against it.

**Comment by ginggs** [comment]
To answer some of your questions:

**uname -a** on amd64
```
Linux autopkgtest 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**uname -a** on s390x
```
Linux autopkgtest 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:57:22 UTC 2020 s390x s390x s390x GNU/Linux
```

> The actual tests are executed either in ephemeral VMs in ScalingStack or within lxc containers managed via lxd which is also running on ScalingStack VMs. [1]

I think amd64 and s390x are both using lxc containers.  The only architecture still using VMs is armhf.

I haven't been able to find the output of **cat /proc/cpuinfo**.  I can try asking around during the week.



[1] https://wiki.ubuntu.com/ProposedMigration/AutopkgtestInfrastructure#Worker_service_in_the_cloud

**Comment by gaborcsardi** [comment]
Thanks for the info! Yeah, I think this mostly (only?) happens in containers. Somehow docker/lxd/lxc (?) changes the boot time of the container, when the system clock changes, and seemingly also when the host machine sleeps. This is certainly not something that I expected, and it is not really documented, either. 

> I haven't been able to find the output of cat /proc/cpuinfo. I can try asking around during the week.

No worries, it is not important any more. :)

**Comment by gaborcsardi** [comment]
@ginggs Thanks much for the help, the new version of processx is on CRAN already.

**Comment by ginggs** [comment]
@gaborcsardi You are welcome, and thanks to you too!

I uploaded processx 3.4.2 with a patch (as 3.4.2-1ubuntu1) to Ubuntu earlier, and we have green lights on all architectures for the groovy (upcoming 20.10) release.
http://autopkgtest.ubuntu.com/packages/r/r-cran-processx

We'll pick up 3.4.3 once Debian package it from CRAN.
