### ISSUE TITLE
processx::run crashes eclipse

### ISSUE THREAD

**Issue by kforner** [r-lib/processx#266]
I have a test suite that when run inside eclipse/statET crashes it almost on each execution.
It is not completely reproducible and I could not manage to make a minimal reproducible example.

I'm using `parallel::mclapply()` in the code called by the tests. 

I know that without a nice reproducible example this report is not really useful, but hope it can help you to fix these types of issues.
Switching to plain `system()` fixed the issue, lowering the crash rate from ~95% to 0.

I'm open to any suggestions to narrow down the problem.

**Comment by gaborcsardi** [comment]
> I'm open to any suggestions to narrow down the problem.

* Minimal or not, a reproducible example is still the best.
* OS, R version, etc.?
* Was it OK with earlier processx versions?
* Stack trace?
* Does it crash outside of eclipse?
* Are you using this https://github.com/r-lib/processx/pull/237 ?

**Comment by kforner** [comment]
everything's running from a docker container
- host is ubuntu x86_64
- container is debian 9.11
- R version 3.6.1 (2019-07-05)
- processx 3.4.2 (installGithub.r r-lib/processx@v3.4.2)
- no stack trace --> it kills the eclipse process
- it does not crash outside eclipse
- I suppose I am using #237  since I use 3.4.2

In eclipse StatET, the R process is run from a java thread, i.e. you can not see a R process on the system. I suppose it directly uses libR.so.

**Comment by gaborcsardi** [comment]
> no stack trace --> it kills the eclipse process

Sorry, I meant the C stack trace. E.g. if you attach gdb to the process, then you can get a stack trace.

> In eclipse StatET, the R process is run from a java thread, i.e. you can not see a R process on the system. I suppose it directly uses libR.so.

There is still a process, see `Sys.getpid()` for its pid and then attach to it from gdb.

A script that crashes would still be great. Thanks!

**Comment by kforner** [comment]
The problem is that I haven't kept my code changes where I used `processx::run`.
I just tried to replicate those by switching again to processx but it does not crash any longer...

Maybe I some of my `processx::run` calls were wrong. Anyway I'll close this issue until I'm able to reproduce it.
Thanks for your time.

**Comment by gaborcsardi** [comment]
Well, it should not crash, even if your calls are "wrong". So please re-open if you see crashes again.
