### ISSUE TITLE
Supply standard input

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/processx#27]
The best would be if we could write to it from R, but it is unlikely that I can implement that on windows.

**Comment by krlmlr** [comment]
I was looking for this functionality. Too bad it's not there yet, wanted to implement a REPL in a child process...

What problems are you anticipating on Windows?

**Comment by gaborcsardi** [comment]
> I was looking for this functionality. Too bad it's not there yet, wanted to implement a REPL in a child process...

This is particularly tricky to implement in a way that avoids deadlocks. The `stdout` and `stderr` connections have an OS write-side buffer, and if that gets full, the child process blocks at the next write. It is not hard to get into a situation where both processes are waiting for the other one. We would need a method that smartly reads/writes from/to stdout/stderr/stdin, something like Python's `communicate`: https://docs.python.org/2/library/subprocess.html#popen-objects

> What problems are you anticipating on Windows?

I don't know, I forgot. :( Probably not relevant any more, since there is a completely new connection implementation now.

**Comment by predict-r** [comment]
This would be a very nice feature 👍 

With it, I imagine interprocess communication with long running docker containers and clusters, valuable for orchestrating things from within R.

Node.js also can write : https://nodejs.org/api/child_process.html#child_process_subprocess_stdin

**Comment by gaborcsardi** [comment]
Closed by  #114

**Comment by mmuurr** [comment]
Is it possible to add this to `run()`, too?

An example where it'd be nice to use `run()`'s built-in synchronous process management is something like calling `pandoc` where the `stdin` is a string and we can capture the `stdout` into another string directly. Ways to do this now include writing some wrapping management around `process$new()` or writing the input string to a file and calling pandoc on that file, then deleting the file, which seems like overhead.

Either way, thanks much for `processx`; very useful!

**Comment by gaborcsardi** [comment]
@mmuurr can you pls open a new issue for this?

**Comment by mmuurr** [comment]
@gaborcsardi done.
