### ISSUE TITLE
Can't run .cmd files in Windows without the full filename

### ISSUE THREAD

**Issue by nateGeorge** [r-lib/processx#273]
I'm in Windows 10, trying to run the orca CLI from plotly (`plotly::orca()`) which uses `processx::run()`.  It doesn't work (see issue here: https://github.com/ropensci/plotly/issues/1741).  I noticed that `run('orca.cmd')` works.  Any ideas why it doesn't work with simply `run('orca')` and how it can be fixed?

**Comment by nateGeorge** [comment]
Alright, I figured it out.  Originally, I had installed orca with conda: `conda install -c plotly plotly-orca`.  This installed orca.cmd to C:\Users\myusername\Anaconda3\orca.cmd.  I had to install orca from the windows release (https://github.com/plotly/orca/releases/tag/v1.3.1), which it installed to C:\Users\myusername\AppData\Local\Programs\orca.exe.  Then I added this path to my System Path env variable, logged out and back in, and it worked.

For some reason, in Windows, processx doesn't seem to work with .cmd files without using the extension, but can run .exe files with or without the extension.

**Comment by gaborcsardi** [comment]
processx does not look for `.bat` or `.cmd` files currently, only `.com` and `.exe`. It seems that `cmd.exe` looks for `.bat` and `.cmd` _after_ `.exe`, so we could support it without breaking things, even though in theory this is a breaking change.

**Comment by gaborcsardi** [comment]
[accidental close]

This needs to be added here: https://github.com/r-lib/processx/blob/447dab47698b7ca52b43f9e2d267c1c8844aedd4/src/win/processx.c#L659-L666
with a unit test ideally.

**Comment by gaborcsardi** [comment]
Actually, the documentation of `CreateProcess()` says, that it cannot open `.bat` and `.cmd` files directly, and you need to start a shell:

>To run a batch file, you must start the command interpreter; set lpApplicationName to cmd.exe and set lpCommandLine to the following arguments: /c plus the name of the batch file.

https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw

This is clearly not what we are seeing, but it is still not a good idea to implement something that should not work according to the docs.

So I'll close this now.

**Comment by pokyah** [comment]
Hi!

I'm facing the same problem as @nateGeorge while using orca called by an R script from KNIME. 

R throws me the following error:

`command orca not found @win/processx.c:983 (processx_exec)` 

I can get rid of it by tweaking https://github.com/pokyah/plotly/blob/master/R/orca.R at line 97 so that it call `system `instead of `processx`. However I consider this as a hotfix rahter than a permanent solution.

How could we efficiently investigate and solve the problem on the processx side? 

I'll be keen to help.

Thanks

**Comment by gaborcsardi** [comment]
@pokyah This is how you can start a `.cmd` file: https://processx.r-lib.org/reference/process.html#batch-files

**Comment by pokyah** [comment]
Thanks @gaborcsardi. Will check how to understand your link in order to implement a solution for https://github.com/ropensci/plotly/blob/master/R/orca.R

**Comment by gaborcsardi** [comment]
This should work I believe:

```r
process$new("cmd.exe", c("/c", "orca"))
```
