### ISSUE TITLE
Launch process with default environment, without inheritance

### ISSUE THREAD

**Issue by mkirzon** [r-lib/processx#274]
## Ask
By default, `env=NULL` when launching `process$new()` means that the subprocess inherits the parent's envirnoment. I'm looking for an easy way to launch a subprocess as if it was launched from the OS directly. 

## Context
I'm trying to launch RScript commands from one version of R interactively, to launch R sessions in other R versions. This is very error prone since the R-version-specific user library (R_LIBS_USER) is passed down to the other R sessions. 

## Workaround
I tried passing an empty vector like `env=c()` but found this has the same effects as `env=NULL`. 
I found that passing a dummy variable overwrites the behavior `env=c(zzzzz = "dummy")` and correctly resets the environment to more or less the "default"

**Comment by gaborcsardi** [comment]
> I tried passing an empty vector like env=c() but found this has the same effects as env=NULL.

Well `c()` is `NULL`, really, so that will not work:

```r
❯ c()
NULL
```

If you really don't want any environment variables, then use `character()`. But I am not sure if that's a good idea, because the system and users do set some environment variables to configure R and other processes, so you probably want to keep (some of?) those. E.g. `HOME`, `TMPDIR`, `LANG`, etc.

> By default, env=NULL when launching process$new() means that the subprocess inherits the parent's envirnoment. I'm looking for an easy way to launch a subprocess as if it was launched from the OS directly.

Well, there is no such thing on any OS, basically. Every process is started by another process, except for the first one, which is started by the kernel, once loaded.

I think what you probably want is to clean up the environment of the current process, and pass that to the sub-process. I.e. take `Sys.getenv()` and then remove every env var that starts with `R_`.

Another way, that might work is to use the environment of the parent process, as it looked when it was started. This looks nice and clean, e.g. on macOS:

```r
❯ ps::ps_environ(ps::ps_parent(ps::ps_handle()))
__CF_USER_TEXT_ENCODING
                        0x0:0:0
Apple_PubSub_Socket_Render
                        /private/tmp/com.apple.launchd.F3eYyeuGU8/Render
COLORFGBG               15;0
COLORTERM               truecolor
DISPLAY                 /private/tmp/com.apple.launchd.lEwXsi96Z2/org.macosforge.xquartz:0
HOME                    /Users/gaborcsardi
ITERM_PROFILE           Default
ITERM_SESSION_ID        w0t0p0:AD8F098D-C9D2-4403-BD5D-9A7EAD1C5F3D
LANG                    en_US.UTF-8
LC_TERMINAL             iTerm2
LC_TERMINAL_VERSION     3.3.12
LOGNAME                 gaborcsardi
PATH                    /usr/bin:/bin:/usr/sbin:/sbin
PWD                     /Users/gaborcsardi
SHELL                   /bin/zsh
SSH_AUTH_SOCK           /private/tmp/com.apple.launchd.P0ygVLT3r3/Listeners
TERM                    xterm-256color
TERM_PROGRAM            iTerm.app
TERM_PROGRAM_VERSION    3.3.12
TERM_SESSION_ID         w0t0p0:AD8F098D-C9D2-4403-BD5D-9A7EAD1C5F3D
TMPDIR                  /var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/
USER                    gaborcsardi
XPC_FLAGS               0x0
XPC_SERVICE_NAME        0
```

One caveat is that the parent process might not exist any more, so you would need to handle errors and have a fallback.

Another possibility is to use the environment of the current process when it was started, but on Unix R is a shell script, and this sets up some env vars already for the R binary. Similarly on Windows. Nevertheless, maybe this is easier to clean up:

```r
ps::ps_environ(ps::ps_handle())
```

But note that `ps` is only available on the three main platforms, so you need to have another way on others, if you need portable code.

**Comment by mkirzon** [comment]
Thanks for that detailed take on my challenge! 

Can you explain why my workaround seems to have worked? 

Also I tried using your second approach. To get a usable named char vector to pass in to `process$new()`, I had to do a few more steps. Is this what you had in mind? 
```r
# Get list of env vars for parent process
env_par = ps::ps_environ(ps::ps_parent(ps::ps_handle())) 

# Strip the Dlist class so that it works with `processx`
attr(env_par, "class") = NULL

# Remove some weird unnamed variables
env_par = env_par[nchar(names(env_par)) > 0] 

process$new(env = env_par, ...)
```

Considering the above is kind of messy, I think the Sys.env() method may be my best bet (unless my workaround is valid...)
```r
env_par = Sys.getenv()
env_par = env_par[!grepl("^R_", names(env_par))]
```

**Comment by gaborcsardi** [comment]
> Can you explain why my workaround seems to have worked?

You mean `env = c(zzzzz = "dummy")`? Well, it works for some definition of "works". But again, You are not passing `HOME`, `TMPDIR`, etc. and some R code will definitely have problem with these missing. But if that works for you, that's fine. Just be aware that some R code will fail.

> Also I tried using your second approach. To get a usable named char vector to pass in to process$new(), I had to do a few more steps. Is this what you had in mind?

No, you don't need to do anything with it, just pass it directly:

```
env_par <- ps::ps_environ(ps::ps_parent(ps::ps_handle()))
rp <- processx::process$new("R", c("-q", "--vanilla"), env = env_par, stdout = "|", stderr = "|", stdin = "|")
rp$write_input("Sys.getenv()\n")
close(rp$get_input_connection())
cat(rp$read_all_output())
```

```
> Sys.getenv()
EDITOR                  vi
HOME                    /home/csardi
HOSTTYPE                x86_64
LANG                    C.UTF-8
LD_LIBRARY_PATH         /usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
LN_S                    ln -s
LOGNAME                 csardi
MAKE                    make
NAME                    DESKTOP-LAS8LOO
PAGER                   /usr/bin/pager
...
```

**Comment by mkirzon** [comment]
I'm running into an issue with the named Dlist class coming from ps (hence my attribute modification in my previous comment) -
``` r
env_par <- ps::ps_environ(ps::ps_parent(ps::ps_handle()))
rp <- processx::process$new("R", c("-q", "--vanilla"), env = env_par, stdout = "|", stderr = "|", stdin = "|")
#> Error in assert_that(is_string(command), is.character(args), is_string_or_null(stdin), : is.null(env) || is_named_character(env) is not TRUE
```

```r
sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_0.3.0

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11  knitr_1.29       whisker_0.4      magrittr_1.5     R6_2.4.1         rlang_0.4.6      fansi_0.4.0      tools_3.4.2     
 [9] xfun_0.17        cli_2.0.2        clipr_0.7.0      htmltools_0.5.0  ellipsis_0.3.0   assertthat_0.2.1 digest_0.6.25    tibble_3.0.1    
[17] lifecycle_0.2.0  crayon_1.3.4     processx_3.4.4   callr_3.4.3      vctrs_0.3.0      fs_1.5.0         ps_1.4.0         glue_1.4.1      
[25] evaluate_0.14    rmarkdown_2.1    compiler_3.4.2   pillar_1.4.3     pkgconfig_2.0.3
```
<sup>Created on 2020-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
Interesting. It seems that on windows `ps_environ()` returns an env var
with an empty string as the name. You indeed need to remove that entry.

**Comment by mkirzon** [comment]
One update on this - 
So I had it mostly working and the code works as intended using the fix proposed above. However, where I found this fails is in testthat unit tests. Specifically when the unit tests are run in RStudio with the Ctrl+Shift+T shortcut, rather than when run from the console / interactively. 

My suspicion is that RStudio kicks off the tests in yet another subprocess. If that's the true, then the capture of the parent environment is just preserving the parent environment of the R session

**Comment by gaborcsardi** [comment]
I am closing this, as it seems that there is nothing to do in processx.
