### ISSUE TITLE
Error: <rlib_error in process_get_error_connection(self, private):  stderr is not a pipe.>

### ISSUE THREAD

**Issue by BS1125** [r-lib/processx#277]
Hi, My R CMD check on github actions failed because of the following error from the process_get_error_connection function.  I tried rerunning a github action job that passed the CMD check succesfully ten days ago, but it failed today: 

Error: <rlib_error in process_get_error_connection(self, private):
 stderr is not a pipe.>

 Stack trace:

 1. rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
 2. withr:::with_dir(dirname(targz), do_check(targz, package = desc$get("Packag ...
 3. base:::force(code)
 4. rcmdcheck:::do_check(targz, package = desc$get("Package")[[1]],  ...
 5. withr:::with_envvar(c(R_PROFILE_USER = profile, R_LIBS_USER = rlibsuser),  ...
 6. base:::force(code)
 7. callr:::rcmd_safe("check", cmdargs = c(basename(targz), args),  ...
 8. callr:::run_r(options)
 9. base:::with(options, with_envvar(env, do.call(processx::run,  ...
 10. base:::with.default(options, with_envvar(env, do.call(processx::run,  ...
 11. base:::eval(substitute(expr), data, enclos = parent.frame())
 12. base:::eval(substitute(expr), data, enclos = parent.frame())
 13. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args = real_cmd ...
 14. base:::force(code)
 15. base:::do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 16. (function (command = NULL, args = character(), error_on_status = TRUE,  ...
 17. base:::tryCatch(run_manage(pr, timeout, spinner, stdout_line_callback,  ...
 18. base:::tryCatchList(expr, classes, parentenv, handlers)
 19. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 20. value[[3L]](cond)
 21. base:::paste0(resenv$stderr, pr$read_error(), pr$read_error())
 22. pr$read_error()
 23. processx:::process_read_error(self, private, n)
 24. processx:::process_get_error_connection(self, private)
 25. throw(new_error("stderr is not a pipe."))

 x stderr is not a pipe.

**Comment by gaborcsardi** [comment]
> My R CMD check on github actions failed

Which one?

**Comment by BS1125** [comment]
These two:

https://github.com/BS1125/CMAverse/runs/1336377398?check_suite_focus=true

https://github.com/BS1125/CMAverse/runs/1335157829?check_suite_focus=true

**Comment by gaborcsardi** [comment]
These both seem to have timeouted after six hours. The errors you got is probably just a side effect of the timeout.

**Comment by BS1125** [comment]
But this error didn’t appear last time I ran it

**Comment by gaborcsardi** [comment]
Well, CRAN processx did not change since you last time ran it. I think that the chance that this is caused by processx is very low. 

If you think that it is caused by processx, then please try to create a test suite that does not take 4-6 hours to run, so I can run it.
