### ISSUE TITLE
is there a way to redirect stdout to a compressed file ?

### ISSUE THREAD

**Issue by aaelony** [r-lib/processx#278]
Hi -

I'd like to use `processx::run` in a fashion akin to  

```
hive -e 'select * from blah' | gzip > my-huge-file.tsv.gz
```  

I seek the status of the command and the output to go to compressed file, rather than stdout since the output can be truly large.

```
myproc <- processx::run('hive', c('-e', 'select * from blah' | gzip > my-huge-file.tsv.gz')) 
```
doesn't appear to work.  Is there another way to do it? 

Thanks

**Comment by gaborcsardi** [comment]
You cannot run two processes (`hive` + `gzip`) with one `processx::run()` call. If you want this you have three options:
1. Use `system()`, which starts a shell to start the two processes. You lose the processx features of course, so you'll have to start quoting your command line, you cannot interrupt the process, etc.
2. If you need this on Unix only, create a FIFO with `mkfifo` (the Unix command, not the R function), and then start two processes, `gzip` in the background with `processx::process$new()` and `hive` in the foreground. `gzip` will read from the fifo, `hive` will write to it.
3. Start a shell, and supply the command line to it. I.e. something like 
```
processx::run("sh", c("-e", "hive -e 'select * from blah' | gzip > my-huge-file-tsv.gz"))
```
But you'll need to quote the arguments to the shell I am afraid.

I think processx could have a helper function to do option number 2, it is fairly easy to implement, so you wouldn't need to do the quoting, and we could make it work with named pipes on Windows as well.

**Comment by aaelony** [comment]
Thanks for this. 

I'm less concerned about interrupting the process than I am about halting on error.   I'm on centos so I'll try out each of the above.  

My other concern is that if I were only to run the hive command, a huge dataset might accumulate in stdout.  Ideally, I'd like to invoke processx::run with a `hive` command that might return a `data.table` where the dimensions might be GB in size.  Perhaps my intuition is wrong here but converting the `stdout` to a `data.table` seems more efficient via file than the `processx` object, no?

**Comment by gaborcsardi** [comment]
Putting all data into the standard output and then parsing form there is indeed a no-go. 

I think number 2 above is a good use case for you. The downside is that you'll need to manage one or two background processes.

**Comment by aaelony** [comment]
A friend pointed me to the following which works for me with `system` as well: https://stackoverflow.com/questions/31424456/how-to-redirect-output-of-a-program-only-if-it-succeeded/31424574#31424574

In any case, all set now.  

Many thanks for a great library that I'll use in the future!
