### ISSUE TITLE
Spinner Argument

### ISSUE THREAD

**Issue by msgoussi** [r-lib/processx#279]
Plotly orca is using your package in the background ie
 invisible(processx::run("orca", args, echo = TRUE, 
        spinner = TRUE, ...))

library(plotly)
p <- plot_ly(z = ~volcano) %>% add_surface()
orca(p, "surface-plot.png")

my question is very, how to stop spinner ????? if you can help ....

**Comment by gaborcsardi** [comment]
You can capture the output with `capture.output()`. E.g.

```
❯ capture.output(ret <- processx::run("sleep", "5", spinner = TRUE))
[1] "\r-\r\r\\\r\r|\r\r/\r\r-\r\r\\\r\r|\r\r/\r\r-\r\r\\\r\r|\r\r/\r\r-\r\r\\\r\r|\r\r/\r\r-\r\r\\\r\r|\r\r/\r\r-\r\r\\\r\r|\r\r/\r\r-\r\r \r"

❯ ret
$status
[1] 0

$stdout
[1] ""

$stderr
[1] ""

$timeout
[1] FALSE
```
