### ISSUE TITLE
Process finishing unexpectedly

### ISSUE THREAD

**Issue by clente** [r-lib/processx#284]
First of all, thanks for the amazing package.

I'm currently trying to implement the [UCI](https://en.wikipedia.org/wiki/Universal_Chess_Interface) protocol for chess engines in R. The following issue happens when trying to run [Stockfish](https://github.com/official-stockfish/Stockfish) with `{processx}`.

When running the program via command line (installed with `sudo apt install stockfish`), the process starts and waits for user input, but, when trying to spawn a process via `{processx}`, it almost instantly dies.

``` r
# Spawn background process
p <- processx::process$new("stockfish")

# Wait a short while
Sys.sleep(1)

# Check if it's alive
p
#> PROCESS 'stockfish', finished.
```

<sup>Created on 2020-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Sorry if the reprex is not reproducible, but I couldn't find another example. Please let me know if the problem is on my end and/or not related to `{processx}`.

**Comment by gaborcsardi** [comment]
Processx sets stdin to `/dev/null` by default, so the subprocess does not read anything. If you want to send commands through stdin, and get the output from stdout/stderr, do this:

```r
p <- processx::process$new("/usr/games/stockfish", stdin = "|", stdout = "|", stderr = "|")
cat(p$read_output())
#> Stockfish 11 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
```

```r
p$write_input("position fen 8/7p/6p1/5p2/Q4P2/2p3P1/3r3P/2K1k3 w - - 2 44\n")
p$write_input("go\n")
```

```r
p$poll_io(1000)
#>   output    error  process
#>  "ready" "silent" "nopipe"
cat(p$read_output())
#> info depth 1 seldepth 1 multipv 1 score cp 404 nodes 28 nps 28000 tbhits 0 time 1 pv h2h3
#> info depth 2 seldepth 2 multipv 1 score cp 486 nodes 94 nps 94000 tbhits 0 time 1 pv h2h3 c3c2 a4e8 d2e2
#> info depth 3 seldepth 4 multipv 1 score cp 1117 nodes 321 nps 160500 tbhits 0 time 2 pv a4a7 d2h2 a7g1 e1e2 g1h2 e2f3 h2h7 f3g3 h7g6 g3f4
#> info depth 4 seldepth 7 multipv 1 score cp 436 nodes 659 nps 329500 tbhits 0 time 2 pv a4e8 d2e2 e8c8 e2h2 c8c3 e1f2
#> info depth 5 seldepth 7 multipv 1 score cp 512 nodes 789 nps 394500 tbhits 0 time 2 pv a4a7 h7h5 h2h3 d2d1 c1c2
#> info depth 6 seldepth 7 multipv 1 score cp 691 nodes 944 nps 472000 tbhits 0 time 2 pv a4a7 h7h5 h2h3 d2d1 c1c2
#> info depth 7 seldepth 8 multipv 1 score cp 717 nodes 1611 nps 537000 tbhits 0 time 3 pv a4a7 h7h5 h2h3 d2f2 a7e3 e1f1 e3c3
#> info depth 8 seldepth 12 multipv 1 score cp 697 nodes 4320 nps 1080000 tbhits 0 time 4 pv a4a7 h7h5 a7e3 e1f1 e3c3 d2h2 c3g7 f1g2
#> info depth 9 seldepth 12 multipv 1 score cp 692 nodes 5732 nps 1146400 tbhits 0 time 5 pv a4a7 h7h5 a7e3 e1f1 e3c3 d2h2 c3g7 f1g2 g7g6 h2h3 g6f5 g2g3 f5g5 g3f3
#> info depth 10 seldepth 18 multipv 1 score cp 678 nodes 17470 nps 1455833 tbhits 0 time 12 pv a4a7 h7h6
#> bestmove a4a7 ponder h7h6
```

I don't really know stockfish, but it seems that you probably want to have a loop that has `poll_io()`, and then `read_output_lines()` and keep doing this until you get `bestmove...`, or maybe you can also send an interrupt with `interrupt()` if you don't want to wait any more.

**Comment by clente** [comment]
Thank you so much for the help. I didn't understand what `"|"` meant when reading the documentation, but now it makes perfect sense.

If you want to check out the project, it lives at [curso-r/stockfish](https://github.com/curso-r/stockfish) and is going to become a dependency of another package of mine: [curso-r/chess](https://github.com/curso-r/chess). Both [rosawojciech/bigchess](https://github.com/rosawojciech/bigchess) and [oganm/stockfisher](https://github.com/oganm/stockfisher) already have something like this implemented, but  I'm going for a more functional approach.

**Comment by gaborcsardi** [comment]
Cool!
