### ISSUE TITLE
Supervised processes leave supervisor running

### ISSUE THREAD

**Issue by richfitz** [r-lib/processx#294]
This is obviously a design decision, but something that is causing an issue writing an example with a supervised process.

```r
px <- processx::process$new("sleep", "100", supervise = TRUE)
showConnections()
px$kill()
showConnections()
```

I've got something using callr that uses a supervised process, and an example with that; it causes an issue with R CMD check because it checks for left-over connections (share/R/examples-header.R)

```
           ## stop in case users left connections open,
           ## also indicating that parallel cluster are still running
           if(Sys.getenv("_R_CHECK_CONNECTIONS_LEFT_OPEN_", FALSE)){
               sC <- showConnections()
               if(nrow(sC)){
                   stop("connections left open:\n",
                       paste(apply(sC[,1:2, drop = FALSE], 1L, function(x)
                           paste0("\t", x[1L], " (", x[2L], ")")), collapse="\n"),
                                       call. = FALSE, domain = NA)
               }
           }
```

A build failure showing this: https://github.com/mrc-ide/heartbeatr/runs/2193658155

Is there any route around this?

**Comment by gaborcsardi** [comment]
I can export `processx:::supervisor_kill()` if that's OK?

**Comment by richfitz** [comment]
Is there any way of calling that "politely"? So kill the supervisor if it's not supervising anything else?

**Comment by gaborcsardi** [comment]
Potentially, but if you need this to work around some check failure, then I think you'd want to just kill it, together will all the other sub-processes. No?

**Comment by richfitz** [comment]
yeah, I can do that in the example for sure (and can use the `:::` version in the meantime to do that - thanks)

**Comment by gaborcsardi** [comment]
Oh, it is an example. Sorry, I thought it was a test case. 

Can you maybe add the killing to the example, and put it in `\dontshow{}`? Would that make sense?

**Comment by richfitz** [comment]
Yes, that makes sense thanks

**Comment by gaborcsardi** [comment]
So do you still want me to export some api from `https://github.com/r-lib/processx/blob/master/R/supervisor.R`? `supervisor_kill()` and `supervisor_running()`?

**Comment by richfitz** [comment]
It looks like just `supervisor_kill` would be enough - I've got R CMD check happy with that at least. I can put that behind `interactive()` to stop the example being antisocial.

Practically this won't run on CRAN because it requires a redis server

**Comment by gaborcsardi** [comment]
OK, we just had a release, but I'll export it in the next one.

**Comment by richfitz** [comment]
Amazing, thank you 🙏  - we're still a way off releasing the thing that this is needed for to CRAN 🐌
