### ISSUE TITLE
To remove 00LOCK-processx.

### ISSUE THREAD

**Issue by lennyzhlin** [r-lib/processx#295]
After I executed installation > devtools::install_github("nstrayer/datadrivencv")

I got the following messages:
Downloading GitHub repo nstrayer/datadrivencv@HEAD
Installing 1 packages: processx
Installing package into ‘C:/Users/zihao/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
         binary source needs_compilation
processx  3.4.5  3.5.0              TRUE

installing the source package ‘processx’

trying URL 'https://cran.rstudio.com/src/contrib/processx_3.5.0.tar.gz'
Content type 'application/x-gzip' length 138856 bytes (135 KB)
downloaded 135 KB

ERROR: failed to lock directory 'C:/Users/'myname'/Documents/R/win-library/4.0' for modifying
Try removing 'C:/Users/'myname'/Documents/R/win-library/4.0/00LOCK-processx'
Error: Failed to install 'datadrivencv' from GitHub:
  (converted from warning) installation of package ‘processx’ had non-zero exit status

**Comment by gaborcsardi** [comment]
This is a lock file created by `install.packages()`, processx has nothing to do with this. The solution is to remove the lock file as the message itself says.

**Comment by lennyzhlin** [comment]
> This is a lock file created by `install.packages()`, processx has nothing to do with this. The solution is to remove the lock file as the message itself says.

You made my day.  Awesome.

I found the solution, here was the code I commended.

unlink("C:/Users/'myname'/Documents/R/win-library/4.0/00LOCK-processx", recursive = TRUE)
