### ISSUE TITLE
Stop supervisor

### ISSUE THREAD

**Issue by markwsac** [r-lib/processx#306]
Thanks for this lovely package. I am using chromote package which uses  `processx::process$new(.., supervise=T)` sometimes starting a session in chromote ` b <- chromote::ChromoteSession$new()` does not work properly because it stopped earlier forcefully so I have to restart R to make it work. I got to know from the [issue](https://github.com/rstudio/chromote/issues/23) that Once the processx supervisor is started, it keeps running until the R process ends, and there's no mechanism for stopping it.  To workaround this I tried `.rs.restartR(); print('Hello World')` but problem is after restarting it does not go to the next line of code.  Just wondering if any way now with new updates? Thanks in advance!

**Comment by gaborcsardi** [comment]
I don't really understand why you need this, but if you want to stop the supervisor, you can call `processx::supervisor_kill()`.
