### ISSUE TITLE
Allow PROCESSX_NOTIFY_OLD_SIGCHLD to be set after processx is loaded?

### ISSUE THREAD

**Issue by wlandau** [r-lib/processx#310]
From #237:

>This is now opt in, and the PROCESSX_NOTIFY_OLD_SIGCHLD env var has to be set (to any value), at the time of loading of the processx package.

Are there plans to relax the restriction about setting the env var before loading `processx`? This would help unit testing for packages that depend on `processx`. For `targets`, I need to set `PROCESSX_NOTIFY_OLD_SIGCHLD=true` in `~/.Renviron` to avoid "Error while shutting down parallel: unable to terminate some child processes". `Sys.setenv(PROCESSX_NOTIFY_OLD_SIGCHLD = "true")` in the package's `.onLoad()` or `tests/testthat.R` is already too late.

Somewhat related: https://github.com/mschubert/clustermq/discussions/266

**Comment by gaborcsardi** [comment]
> or `tests/testthat.R` is already too late.

That should not be too late, this file runs with no packages loaded.

**Comment by wlandau** [comment]
At first I thought it would not be too late, but I still see "Error while shutting down parallel: unable to terminate some child processes" even if I write `Sys.setenv(PROCESSX_NOTIFY_OLD_SIGCHLD = "true")` in the first line of `tests/testthat.R`. Could it be that I am running tests through `devtools::test()` and `devtools` depends on `callr`?

**Comment by gaborcsardi** [comment]
`devtools::test()` does not use `tests/testthat.R`.

For `devtools::test()` set it in your user's `.Renviron`. 

For `R CMD check` set it in `tests/testthat.R` before you load any package.
