### ISSUE TITLE
Unable to Install Packages From GitHub (System Error 267 @win/processx.c:1040)

### ISSUE THREAD

**Issue by Buedenbender** [r-lib/processx#313]
Full disclosure, I already tried my luck with the problem on [Stackoverflow](https://stackoverflow.com/questions/68400661/r-unable-to-install-packages-from-github-system-error-267-win-processx-c1040). 

The basic problem is, that I can not install **any package** from github on my machine. I tried `remotes::install_github()` as well as `devtools::install_github()`, however both fail with a reference to `processx.c:1040` and `system error 267`. One example would be [rstudio/gt](https://github.com/rstudio/gt) but the error is the same with other GitHub repos.

```
devtools::install_github("rstudio/gt")
Downloading GitHub repo rstudio/gt@HEAD
Error: Failed to install 'gt' from GitHub:
  create process 'C:/R/bin/x64/Rcmd.exe' (system error 267, Der Verzeichnisname ist ungültig.
) @win/processx.c:1040 (processx_exec)
```

 I followed some advice from [Stackoverflow](https://stackoverflow.com/questions/68400661/r-unable-to-install-packages-from-github-system-error-267-win-processx-c1040) and completely removed special character from paths. E.g. I reinstalled R to `C:/R/` and set `.libPaths()` to `D:/tmp`

### Session Info

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    usethis_2.0.1     devtools_2.4.2    pkgload_1.2.1    
 [6] R6_2.5.0          rlang_0.4.11      fastmap_1.1.0     tools_4.1.0       pkgbuild_1.2.0   
[11] sessioninfo_1.1.1 cli_3.0.0         withr_2.4.2       ellipsis_0.3.2    remotes_2.4.0    
[16] rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1      processx_3.5.2    purrr_0.3.4      
[21] callr_3.7.0       fs_1.5.0          ps_1.6.0          testthat_3.0.4    curl_4.3.2       
[26] memoise_2.0.0     glue_1.4.2        cachem_1.0.5      compiler_4.1.0    desc_1.3.0       
[31] prettyunits_1.1.1
```

**Comment by gaborcsardi** [comment]
> I tried `remotes::install_github()` as well as `devtools::install_github()`

The latter just calls the former.

You can run `remotes::install_github()` without processx, in a clean R session:
```r
Sys.setenv(R_REMOTES_STANDALONE="true")
remotes::install_github("rstudio/gt")
```

If this fails as well, then I am afraid the problem is not in processx.

**Comment by gaborcsardi** [comment]
Also, can you install packages with compiled code from CRAN?
```r
install.packages("ps")
```

```r
install.packages("ps", type = "source")
```

**Comment by Buedenbender** [comment]
Yes I can install packages from source, 
`install.packages("ps", type = "source")`
executed without error.

Thank you for your quick help. And the suggestions, to execute remotes in standalone mode.
```
Sys.setenv(R_REMOTES_STANDALONE="true")
remotes::install_github("rstudio/gt")
```
Took a while to run (since it recompile stingi). After completion it really successfully installed gt from GitHub. Thus it solved my Problem thanks a lot

Final output of the install
```
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (gt)
> library(gt)
```

**Comment by RemPsyc** [comment]
> You can run `remotes::install_github()` without processx, in a clean R session:
> 
> ```r
> Sys.setenv(R_REMOTES_STANDALONE="true")
> remotes::install_github("rstudio/gt")
> ```
> 
> If this fails as well, then I am afraid the problem is not in processx.

@gaborcsardi, this workaround works perfectly in my case, surprisingly. I started experiencing the same problem as OP a few months ago and tried literally everything to fix it to no avail. Fortunately, you found a fix. But I'd like to understand what this command does though. What does it mean that this command fixes the issue—what are the implications?

Are you saying above that the fact that this does not fail implies that the problem _is_ with processx? Could it have been a processx update a couple months ago that started this error? Seems like many users are experiencing this error (e.g., see [RStudio forum](https://community.rstudio.com/t/install-github-system-error-267-the-directory-name-is-invalid/107145/10)).


`Sys.setenv(R_REMOTES_STANDALONE="true")`

**Comment by gaborcsardi** [comment]
> Could it have been a processx update a couple months ago that started this error? 

Can you try installing the previous processx version to check?

**Comment by RemPsyc** [comment]
Good idea! So my current version of `processx` is 3.5.2. I've tried reinstalling it but seems like it's the latest version.

Then tried reinstalling from CRAN source to the previous version:

`install.packages("https://cran.r-project.org/src/contrib/Archive/processx/processx_3.5.1.tar.gz", repos=NULL, type="source")`

But it still resulted in the same error. But then I completely uninstalled the package, and tried the same command again. This time... **_it worked_**. OMG!!! Could we have found the issue??

Could it be related to this change in the last version:

```
processx now works with non-ASCII path names on non-UTF-8 Unix platforms
(#293).
```

Because it seems like all users to which this is happening have non-ASCII username paths...

**Comment by gaborcsardi** [comment]
I am sorry, I don't follow. The remotes functions worked if you uninstalled processx?

**Comment by RemPsyc** [comment]
Sorry, I mean that the remotes function worked after manually uninstalling and then trying the same command again (of install processx). Therefore, the previous version of processx works as expected and does not create an error trying to use `devtools::install_github`.

**Comment by gaborcsardi** [comment]
Got it. It seems that this issue does not come up with English Windows, so I'll have to try to reproduce it on a German one.

**Comment by RemPsyc** [comment]
My Windows is English (Canada) but the issue seems to be in people's usernames containing special accents, not the language of Windows itself. Would you like to try creating a new user with accents in its username?

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5  
```

**Comment by gaborcsardi** [comment]
OK, I can reproduce this if I use a temporary directory name that is non-ascii:

```
> pkgbuild::build()
Error in rethrow_call(c_processx_exec, command, c(command, args), pty,  :
  create process 'C:/PROGRA~1/R/R-41~1.3/bin/x64/Rcmd.exe' (system error 267, The directory name is invalid.
) @win/processx.c:1040 (processx_exec)
Type .Last.error.trace to see where the error occurred
> .Last.error.trace
> .Last.error.trace

 Stack trace:

 1. pkgbuild::build()
 2. withr::with_temp_libpaths(rcmd_build_tools(options$cmd, c(options ...
 3. base:::force(code)
 4. pkgbuild:::rcmd_build_tools(options$cmd, c(options$path, options$ ...
 5. pkgbuild:::with_build_tools({ ...
 6. withr::with_path(rtools_path(), code)
 7. base:::force(code)
 8. base:::withCallingHandlers(callr::rcmd_safe(..., env = env, spinn ...
 9. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  ...
 10. callr:::run_r(options)
 11. base:::with(options, with_envvar(env, do.call(processx::run,  ...
 12. base:::with.default(options, with_envvar(env, do.call(processx::r ...
 13. base:::eval(substitute(expr), data, enclos = parent.frame())
 14. base:::eval(substitute(expr), data, enclos = parent.frame())
 15. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args  ...
 16. base:::force(code)
 17. base:::do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 18. (function (command = NULL, args = character(), error_on_status = TRUE,  ...
 19. process$new(command, args, echo_cmd = echo_cmd, wd = wd, windows_ ...
 20. processx:::initialize(...)
 21. processx:::process_initialize(self, private, command, args, stdin ...
 22. base:::rethrow_call(c_processx_exec, command, c(command, args),  ...

 x create process 'C:/PROGRA~1/R/R-41~1.3/bin/x64/Rcmd.exe' (system error 267, The directory name is invalid.
) @win/processx.c:1040 (processx_exec)
```

**Comment by gaborcsardi** [comment]
It is because of this:
https://github.com/r-lib/processx/pull/303/files#diff-4903894005b24a6006b391b4e332f6e60d0c760a363f4c390c33212099589d12R91

If the current working directory (which is `tmpdir()` for pkgbuild) has non-ascii characters, then `getwd()` returns a shortened path, and then `CreateProcessW()` fails with that. So we just need to call `normalizePath()` to avoid a short path.
