### ISSUE TITLE
Unrecognized arguments: &

### ISSUE THREAD

**Issue by thiagoveloso** [r-lib/processx#314]
I am trying to run a python script that takes a few hours to complete. I am using `nohup` to keep the process running in the background.

In terminal, I would run this command like this:

```
nohup /opt/scripts/gee_fields_S2.py users/inter/20210716-inter 2015-01-01 2015-02-28 --bucket gee-rgb & 
```

With `processx`, I am trying the following:
```
> my.comm
[1] "/opt/scripts/gee_fields_S2.py
[2] "users/inter/20210716-inter"
[3] "2015-01-01"
[4] "2015-02-28"
[5] "--bucket"
[6] "gee-rgb"
[7] "&"

run("nohup", my.comm)
```

But I keep receiving the following error message:

```
Error in run("nohup", my.comm) : 
  System command 'nohup' failed, exit status: 2, stderr:
E> usage: gee_fields_S2.py  [-h] [--folder folder]
E>                          [--bucket bucket]
E>                          [--maxCloud maxCloud]
E>                          aoiPath dateStart dateEnd
E> gee_fields_S2.py: error: unrecognized arguments: &
```

Am I doing something wrong? Or doesn't `processx` support the usage of `&` (ampersand)?

**Comment by gaborcsardi** [comment]
`&` is interpreted by the Unix shell. You don't need it for processx, but you need to use `processx::process$new("nohup", my.comm, cleanup = FALSE)` instead. `run` is not for background processes.

**Comment by thiagoveloso** [comment]
> `&` is interpreted by the Unix shell. You don't need it for processx, but you need to use `processx::process$new("nohup", my.comm, cleanup = FALSE)` instead. `run` is not for background processes.

Amazing, it works!

Thanks for the quick response - and for the awesome package as well!
