### ISSUE TITLE
Test suite error in processx

### ISSUE THREAD

**Issue by tillea** [r-lib/processx#317]
Hi,
I'm trying to update the Debian package of processx (old version in Debian is 3.4.5) to the recent version 3.5.2.  The Debian CI has a [full build log of the package](https://salsa.debian.org/r-pkg-team/r-cran-processx/-/jobs/1821693) where you can obtain the compiler and R version that was used.  Furthermore there is a full log of the test suite that was run.  [Here](https://salsa.debian.org/r-pkg-team/r-cran-processx/-/jobs/1821700#L812) is a deep link to the actual error that is thrown which says

    ══ Failed ══════════════════════════════════════════════════════════════════════
    ── 1. Failure (test-err.R:252:3): errors from subprocess ───────────────────────
    `err` is not an S3 object
    ── 2. Failure (test-err.R:253:3): errors from subprocess ───────────────────────
    err$parent is not an S3 object
    ── 3. Failure (test-err.R:254:3): errors from subprocess ───────────────────────
    is.null(err$parent$trace) is not FALSE
    `actual`:   TRUE
    `expected`: FALSE
    ══ DONE ════════════════════════════════════════════════════════════════════════
    Error: Test failures

I hope this information is sufficient to track down the issue.
Kind regards, Andreas.

**Comment by nileshpatra** [comment]
Hi @gaborcsardi 

Sorry to get on your nerves, but could you please look into this soon-ish? Actually this is the last package which
is stalling the migration of r-base into testing for us.
Hence, a quick action will be greatly appreciated.

Thanks for your work!

**Comment by gaborcsardi** [comment]
I don't know when i can look at this. Can you skip these test cases? They are not very important.

**Comment by nileshpatra** [comment]
Sure, thanks for letting us know!

**Comment by gaborcsardi** [comment]
That also don't fail anywhere else in the several test systems, which suggests that the failures are specific to your test system.
