### ISSUE TITLE
errno is modified in signal handlers

### ISSUE THREAD

**Issue by buchgr** [r-lib/processx#334]
Using [thread sanitizer](https://github.com/google/sanitizers/wiki/ThreadSanitizerDetectableBugs) I found that the signal handler for SIGCHLD `processx__sigchld_callback` https://github.com/r-lib/processx/blob/8a959afb25edb5d8eacd8e30e429a6f78b556aac/src/unix/sigchld.c#L41

may modify `errno`. The fix is to save `errno` when entering and restoring it when exiting the signal handler, like in `processx.c`

https://github.com/r-lib/processx/blob/b7e15fb62758de25f7ed9cc9ceb437f10d6362a3/src/unix/processx.c#L92

I am happy to send a PR, but it's unclear to me yet on how to best write an automated test for it.

**Comment by gaborcsardi** [comment]
Thanks! A PR is welcome. No need to test for it in the PR, but a good test would be to run thread sanitizer on GHA.
