### ISSUE TITLE
hanging bash scripts

### ISSUE THREAD

**Issue by avraam-inside** [r-lib/processx#345]
when running standard scripts (for example:) `run('bash', c('-c', 'ls'))` the session sometimes hangings.

I've already tried everything: `cleanup_tree`, and using R6 methods with `rm(p)` and `gc()` and `kill()` reading outputs:
```r
stderr <-p$read_all_error_lines()
stdout <-p$read_all_output_lines()
```
and etc/etc

NOTHING IS WORKING.

Please tell me a sane way to clear buffers, caches, etc. before/after the script so that run does not hang. This has never happened with the `system()` command at all.

**Comment by gaborcsardi** [comment]
Can you try to create a reproducible example?

**Comment by avraam-inside** [comment]
Да я просто пробовал и через run и через R6. 

Падает на любом коде.

Берет и виснет иногда. Ожидается работа в 4 секунды обычно, иногда отвисает через пару минут. 

Пример как делал: 

`processx::run('bash', c('-c', 'cd /home && R --no-save --no-restore-data --quiet -e "print(\'123\')"'))`

and 

```r
p <- processx::process$new('bash', c('-c', 'cd /home && R --no-save --no-restore-data --quiet -e "print(\'123\')"')), stdout = "|", stderr = "|", wd = here())
    p$poll_io(50000000)
    
    stderr <- p$read_all_error_lines()
    stdout <- p$read_all_output_lines()
    
    close(p$get_output_connection())
    close(p$get_error_connection())
    
    p$kill_tree()
    
    p$kill()
```

**Comment by gaborcsardi** [comment]
> An example of how I did:

This runs in ~ 150ms for me, so that is definitely weird, even if it runs. It also never crashes or hangs for me. What is your platform?

```
system.time({
  p <- processx::process$new('bash', c('-c', 'cd /home && R --no-save --no-restore-data --quiet -e "print(\'123\')")'), stdout = "|", stderr = "|", wd = here::here())
  p$wait()
})
```

This also does not crash, but finishes in ~5ms.

**Comment by avraam-inside** [comment]
It falls only occasionally. But even this is sometimes enough to cause problems.

Ubuntu in container

**Comment by gaborcsardi** [comment]
> Ubuntu in container

That's great, so then can you create a `Dockerfile` that reproduces this?

**Comment by avraam-inside** [comment]
It won't work, there's too much code, the service is on a shiny-proxy, with its own package and oun autotests and renv, the error repeats relatively rarely and there is no clear pattern how to cause it.

But after waiting for n time, I probably found the area with which it is connected - most likely with renv...

It's very strange why it climbs into CRAN. When restarting - everything works normally, the error is not repeated.

![image](https://user-images.githubusercontent.com/52919010/186410918-916596c8-c499-40ac-9f7e-c1b92eef9fcc.png)

If you suddenly have ideas or have encountered them before, I will be glad to help. But it seems that the problem is not in the processч.
