### ISSUE TITLE
Connect to an exisiting R session from a different R session

### ISSUE THREAD

**Issue by talegari** [r-lib/processx#347]
Hi processx dev,

I am attempting to do the following:

1. Use R session1 to create session2 via `callr::r_session` class.
2. Obtain the `ps_handle` and the `pid` of this session2.
3. Start R session3 manually, and then try and connect to session2 to get some job done.

Here is the code:
``` r
s2 = callr::r_session$new()
s2$run(function(){
    x <<- 1L
    return(NULL)
    })
#> NULL

s2$as_ps_handle()
#> <ps::ps_handle> PID=23970, NAME=R, AT=2022-09-11 14:02:44
```

Question: Is it possible to do step 3 as intended above? How to do it (how to connect to the R session running at pid = 23970)?
PS: This question lie at the intersection of `callr`, `processx` and `ps`. Let me know if I have to raise this issue at a different repo.

**Comment by gaborcsardi** [comment]
I am afraid that this is not possible. You could create a `callr::r_session` from a `callr::r_session()`, that should be fine, although debugging it won't be pleasant.
