### ISSUE TITLE
User-defined process name

### ISSUE THREAD

**Issue by wlandau** [r-lib/processx#354]
I think it would be really nice to supply a custom name for a process, similar to the `name` argument of `parallel::mcparallel()`. That way it will be easier to find the process on `htop` or `ps::ps()`. My apologies if this is already possible and I am missing something.

**Comment by gaborcsardi** [comment]
How do you find a `parallel::mcparallel(..., name = "foobar")` process in `htop` or `ps::ps()`?

**Comment by wlandau** [comment]
Hmmm... before I had thought this was possible, but now I am not sure. `future::future()` with the multicore backend calls `parallel::mcparallel()` and forwards the `label` argument of the former to the `name` argument of the latter. With the backends for clusters like SGE and SLURM these labels do show up as job names, but it looks like `htop` only has the concept of a command.
