### ISSUE TITLE
Different behaviour inside and outside functions

### ISSUE THREAD

**Issue by jameslairdsmith** [r-lib/processx#355]
When I try to read output of `ls` from the global environment, it works fine, when I do exactly the same thing within a function defined in the global environment, I get no output.

``` r
library(processx)

p <- process$new("ls", stdin = "|", stdout = "|", stderr = "|")
my_output <- p$read_output()
p$kill()
#> [1] FALSE
my_output
#> [1] "mid-guppy_reprex.R\nmid-guppy_reprex.spin.R\nmid-guppy_reprex.spin.Rmd\n"

my_fun <- function(){
  local_p <- process$new("ls", stdin = "|", stdout = "|", stderr = "|")
  local_output <- local_p$read_output()
  local_p$kill()
  local_output
}

my_fun()
#> [1] ""
```

<sup>Created on 2023-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
`$read_output()` does not block or wait for output, but reads the output so far, which is might be no output at all if the process is just starting up, and then `$kill()` kills the process.

See https://github.com/r-lib/processx#standard-output-and-error

**Comment by jameslairdsmith** [comment]
Worked out why. It seems that adding a short pause in the function version allows it enough time to capture the input. Not sure why it's not required in the global version though? 

``` r
library(processx)

p <- process$new("ls", stdin = "|", stdout = "|", stderr = "|")
my_output <- p$read_output()
p$kill()
#> [1] FALSE
my_output
#> [1] "fine-bluet_reprex.R\nfine-bluet_reprex.spin.R\nfine-bluet_reprex.spin.Rmd\n"

my_fun <- function(){
  local_p <- process$new("ls", stdin = "|", stdout = "|", stderr = "|")
  Sys.sleep(2)
  local_output <- local_p$read_output()
  local_p$kill()
  local_output
}

my_fun()
#> [1] "fine-bluet_reprex.R\nfine-bluet_reprex.spin.R\nfine-bluet_reprex.spin.Rmd\n"
```

<sup>Created on 2023-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jameslairdsmith** [comment]
> `$read_output()` does not block or wait for output, but reads the output so far, which is might be no output at all if the process is just starting up, and then `$kill()` kills the process.
> 
> See https://github.com/r-lib/processx#standard-output-and-error

Sorry, just saw this now.

**Comment by gaborcsardi** [comment]
For the record, a short pause is not a good idea, it is hard to make assumptions about running times, and even if it happens to work, it makes your code slow.

If you always want to wait for the process to end, then use `run()`. You can also use `$wait()` (with a timeout) to wait for a process to end.

**Comment by jameslairdsmith** [comment]
Thanks @gaborcsardi ! I really appreciate you taking the time and the speedy response!
