### ISSUE TITLE
arguments with  special character like \'~\' case an error.

### ISSUE THREAD

**Issue by dtdage** [r-lib/processx#371]
Hi , thank first, this package is very helpful, but I seem to have found a bug.
arguments  with special characters （like ”\~“） will  get extral apostrophes when runnig. which will case an error.
Here is a example.
```r
> library("processx")
> args <- c("~/.bashrc")
> run(command = "cat", args = args, echo_cmd = TRUE)
Running cat '~/.bashrc'
Error in `run(command = "cat", args = args, echo_cmd = TRUE)`:
! System command 'cat' failed
---
Exit status: 1
Stderr:
cat: '~/.bashrc': No such file or directory
---
Type .Last.error to see the more details.
```
please help me!

**Comment by gaborcsardi** [comment]
No, they don't, that's just the printing. 

But processx does not resolve the tilde, the shell does that. So you need to stay a shell or use R to resolve it. I suggest the latter.

**Comment by dtdage** [comment]
> No, they don't, that's just the printing.
> 
> But processx does not resolve the tilde, the shell does that. So you need to start a shell or use R to resolve it with path.expand(). I suggest the latter.

thanks a lot, this solved my problem.
