### ISSUE TITLE
Move httpbin to test-poll-curl.R?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/processx#374]
https://github.com/r-lib/processx/blob/25812a1b98d6a8f993f6799079616fffeae7aa56/tests/testthat/helper.R#L63-L66

This requires Suggests package 'webfakes', but is only used in 'test-poll-curl.R'. It would be better to isolate the dependency of the tests on 'webfakes' to just one test file instead of all files (as helper.R is run before all tests).

Happy to file the PR if you agree.

**Comment by MichaelChirico** [comment]
Moreover every test in `test-poll-curl.R` is a `skip_on_cran()` test, so that object is not needed "most of the time" anyway.

**Comment by gaborcsardi** [comment]
Moving it to a test file creates a much worse development workflow, so I am not going to do that.

Btw. it takes about 0.01s to run that code, or 0.06 is one needs to cold-load the webfakes package:
```
❯ system.time(httpbin <- webfakes::new_app_process(
+   webfakes::httpbin_app(),
+   opts = webfakes::server_opts(num_threads = 6)
+ )
+ )
   user  system elapsed
  0.006   0.005   0.011
```
