### ISSUE TITLE
Quoted command on Windows fails to start process

### ISSUE THREAD

**Issue by wch** [r-lib/processx#62]
On Windows, if there are quotes around the command (when using `commandline`), then it fails to start the process correctly. Or at least the process exits with an error. For example:

```R
library(processx)
p <- process$new(commandline = "echo abc")
p$get_exit_status() # 0

p <- process$new(commandline = '"echo" abc')
Sys.sleep(0.25)
p$get_exit_status() # 1

# Works fine with system()
system('"echo" abc') # abc
```

**Comment by gaborcsardi** [comment]
Yes, windows quotes by default. Try `windows_verbatim_args = FALSE` please.

**Comment by gaborcsardi** [comment]
Also, I know this is not the point here, but if you want to wait for a process to finish, use `$wait()` instead of sleeping.

**Comment by wch** [comment]
```R
p <- process$new(commandline = '"echo" abc', windows_verbatim_args = TRUE)
p$wait()
p$get_exit_status() # 0

p <- process$new(commandline = '"echo" abc', windows_verbatim_args = FALSE)
p$wait()
p$get_exit_status() # 1
```

Why does it quote on Windows by default, but not on other platforms? This caused problems with webdriver and shinytest because they used `shQuote()` on the command -- this worked fine on Mac, but on Windows, the process did not start.

**Comment by gaborcsardi** [comment]
Because windows is fundamentally different, and the application itself parses the arguments. 

Nevertheless, I think just omitting the `shQuote` should work on both platforms. Doesn't it?

**Comment by wch** [comment]
I switched to using `command` and `args`. If I had kept using `commandline` and omitted `shQuote`, wouldn't that cause problems if the path had a space in it?

**Comment by gaborcsardi** [comment]
Yes, `command` & `args` is the better way. Just don't `shQuote` and it should work.

`commandline` is equivalent to `command = "sh"`, `args = c("-c", commandline)` so there you'll need to quote.

**Comment by gaborcsardi** [comment]
It might make sense to change `verbatim` on windows, if `commandline` is given.

**Comment by gaborcsardi** [comment]
I mean we could change the default for `verbatim` in `processx`, when `commandline` is given. 

If I am following everything right here.

**Comment by wch** [comment]
I'm not sure I understand exactly what `windows_verbatim_args` does, but it makes sense to me that if you supply `commandline`, that it would behave like `system()` does.

**Comment by gaborcsardi** [comment]
Yeah, that's exactly what I mean.

**Comment by gaborcsardi** [comment]
I removed the `commandline` argument for now, so I'll close this issue.
