### ISSUE TITLE
Suspend and resume a process

### ISSUE THREAD

**Issue by yihui** [r-lib/processx#73]
I know `tools::pskill()` can send `SIGTSTP` and `SIGCONT`, but according to the documentation, Windows is not supported (only `SIGINT` and `SIGKILL` are supported). Is it possible to support them in processx?

**Comment by gaborcsardi** [comment]
There are no signals on windows, so this cannot be implemented easily. It is possible to stop a process (more precisely all threads of a process), and this would indeed be a nice feature.

**Comment by gaborcsardi** [comment]
@yihui So, I looked into this a bit, and it might be possible to implement it. What is your motivation, btw? When does it make sense to stop a background process and then continue it later?

**Comment by gaborcsardi** [comment]
Makes sense. There is a trick on windows (https://stackoverflow.com/a/11010508/604364 the debugger way) which seems easy, but I am not completely sure if it really works well in practice. Will try soon....

**Comment by gaborcsardi** [comment]
This is now implemented in the `ps` package, submitted to CRAN. To create a `ps_handle` from a `process`, you can do
```r
ps <- ps_handle(px$get_pid(), px$get_start_time())
ps$suspend()
ps$resume()
```

**Comment by yihui** [comment]
Great. Thanks!
