### ISSUE TITLE
Tweak run output

### ISSUE THREAD

**Issue by hadley** [r-lib/processx#78]
Currently yields:

```
Running command /Library/Frameworks/R.framework/Resources/bin/R 
Arguments:
CMD
build
/Users/hadley/Documents/devtools/devtools
--no-resave-data
--no-manual
```

Would be nicer (IMO) with `cat_bullet(col = "grey")` or as wrapped quoted lines

**Comment by gaborcsardi** [comment]
Running /Library/Frameworks/R.framework/Resources/bin/R CMD build \
  /Users/gaborcsardi/works/devtools --no-resave-data --no-manual
```
It avoids quoting arguments that obviously don't need any
quoting.

**Comment by hadley** [comment]
Nice, thanks!

**Comment by hadley** [comment]
I do wonder if we should default to displaying in grey? (But no need to consider for this release)

**Comment by gaborcsardi** [comment]
We can, `processx` already depends on `crayon`....
