### ISSUE TITLE
Add windows examples

### ISSUE THREAD

**Issue by danielsjf** [r-lib/processx#80]
When trying your package on Windows I was missing some Windows examples. Much of the code in the readme doesn't work for us. After a few tests I was able to translate most of it, but the learning curve is easier when there are some tested examples.

**Comment by gaborcsardi** [comment]
The difficulty is, that there are not too many standard windows programs that I could use in the examples. There is no `echo`, there is no `sleep`, there is no `ls` (`dir` is a `cmd` command, not an executable that I could start).

I am open to suggestions regarding what external programs to use in windows examples.

**Comment by danielsjf** [comment]
There is an inferior alternative for `sleep` which is `timeout`. This only works as of Windows 7 though. There is a list of some external commands [here](https://superuser.com/questions/229945/where-are-the-standard-windows-prompt-commands-files) (first non-accepted answer). But indeed you're right. It's rather limited.

The dream would be to have a simple parser for linux commands on Windows. Most of the simple executables (e.g. echo, ls, unzip, sh, ...) are included in Rtools for Windows. If the C code would reside somewhere in this project, one could include it in an R package (CRAN doesn't allow executables directly).  Right now, system commands still need to be different for each platform.

**Comment by gaborcsardi** [comment]
There is an executable now, included in the package, `px`, and we use it in the README.
