### ISSUE TITLE
Failing checks not recognized by revdepcheck

### ISSUE THREAD

**Issue by krlmlr** [r-lib/processx#83]
Checking all downstream packages for tibble didn't show any errors, but there are at least two problematic downstream packages. Contents of `README.md` and `problems.md` also looked odd.

Reverting processx to the CRAN version resolved the problem immediately, but I also had to revert r-lib/revdepcheck@d1e6010.

**Comment by gaborcsardi** [comment]
Thanks! Can you please fix the link to the commit? There is no such commit AFAICT.

**Comment by krlmlr** [comment]
Done.

**Comment by gaborcsardi** [comment]
Thanks! Which packages were failing?

**Comment by krlmlr** [comment]
dbplyr and RxODE should be failing but weren't.

**Comment by gaborcsardi** [comment]
Oh, yeah, it is not `processx`, it is just `revdepcheck`, completely broken....

**Comment by gaborcsardi** [comment]
@krlmlr OK, fixed now, sorry. You need to update `rcmdcheck`. (Can also update `revdepcheck`.)

I'll test it on a 64 processor machine now if I can get one.

**Comment by gaborcsardi** [comment]
@krlmlr do you have a tip on where to get a cheap 64 core machine? I can only get max 20 cores for my Azure subscription and AWS is quite expensive....

**Comment by krlmlr** [comment]
You need to file a support request with Azure to increase the 20-core limit. They respond very fast to this, I can now run a machine with size D64S_V3. Works best with an SSD disk, this in turn is easiest with managed disks: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/convert-unmanaged-to-managed-disks.

Note that my default machine had only 30 GB on the system partition which also holds `/tmp`, this doesn't sudfice. My workaround was `TMPDIR=~/tmp R -q -e ...` .

**Comment by krlmlr** [comment]
Can you run 64 cores now on Azure?

**Comment by gaborcsardi** [comment]
No, they haven't changed my limit, still....

**Comment by krlmlr** [comment]
Strange, this took just a few minutes for me. I guess you've filed via their "Help + support / New support request / Quota" dialog in the portal?

**Comment by gaborcsardi** [comment]
Yep. They said 24-48 hours.

**Comment by gaborcsardi** [comment]
Just tried, still max 20 CPU only....
