### ISSUE TITLE
Creating process with supervisor on Windows gives "Error: ms is not a length 1 integer"

### ISSUE THREAD

**Issue by wch** [r-lib/processx#85]
For example, in a clean R session:

```R
processx::process$new('ls', supervise = TRUE)
#> Error: ms is not a length 1 integer
```

Sometimes it gives this error the first or first few times the command is run, then it stops giving the error.

**Comment by gaborcsardi** [comment]
I can't reproduce this:
```
✔ 64 MiB master*
❯ for (i in 1:100) processx::process$new('ls', supervise = TRUE)

✔ 65.2 MiB master*
```

**Comment by wch** [comment]
Sorry, I forgot to mention that this only happens on Windows for me.
