### ISSUE TITLE
ProcessX crash under Windows?

### ISSUE THREAD

**Issue by javierluraschi** [r-lib/processx#90]
Reproes under R and RStudio in Windows 10:

```r
devtools::install_github("rstudio/cloudml", ref = "867d492")
setwd(system.file("examples/mnist", package = "cloudml"))
library(cloudml)
gcloud_install()

cloudml_train()
cloudml_train()
```

From windbg:

<img width="686" alt="screen shot 2017-12-12 at 10 36 02 am" src="https://user-images.githubusercontent.com/3478847/33902276-5ceebff8-df29-11e7-86a5-99fdfa83fc5e.png">

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.1
```

**Comment by gaborcsardi** [comment]
What version of `processx` is this? Looks like the session info is from an empty session. The CRAN version of `processx` does have race conditions. Can you try with the GitHub version? 

I get this, btw:
```
> cloudml_train()
Submitting training job to CloudML...
Error: Unable to retrieve package records for the following packages:
- "processx"
>
```

**Comment by gaborcsardi** [comment]
OK, I think I can reproduce this. I get:
```
c:\Users\Gabor\Documents\R\cloudml\examples\mnist>R -q -e "library(cloudml);cloudml_train()"
> library(cloudml);cloudml_train()
Loading required package: tfruns
Submitting training job to CloudML...
Error in process_initialize(self, private, command, args, stdout, stderr,  :
  Command not found
Calls: cloudml_train ... <Anonymous> -> <Anonymous> -> process_initialize -> .Call
Execution halted
```

**Comment by gaborcsardi** [comment]
OK, there is indeed a bug in `processx`, because it should really not crash.

But, the thing is, processx cannot start a `.cmd` currently, because the `CreateProcess` call that we use does not support that. You need to start a shell, i.e. `cmd.exe` explicitly on windows, unfortunately, and use `gcloud.cmd` instead of `gcloud` (the latter is actually a UNIX shell script).

You also should not quote the command, AFAICT.

From the command line this seems to work: 
```

c:\Users\Gabor\Documents\R\cloudml\examples\mnist>R -q -e "processx::process$new('cmd', c('/c','c:/Users/Gabor/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd'))"
> processx::process$new('cmd', c('/c','c:/Users/Gabor/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd'))
PROCESS 'cmd', running, pid 1852.
>
```

**Comment by javierluraschi** [comment]
@gaborcsardi my bad, looks like running `gcloud_install()` was also required in the instructions, glad you figured this out, I'll update them.

**Comment by gaborcsardi** [comment]
@javierluraschi yeah, unfortunately, the consequence of having to start `cmd.exe` is that we can't easily kill the process, because it will be the child process of `cmd.exe`.

**Comment by javierluraschi** [comment]
Ah, good to know. I'll fix the `cmd.exe` issue on our side, thanks!
